### ISSUE TITLE
std::auto_ptr in 0.27.5 header files

### ISSUE THREAD

**Issue by yangpenglove** [Exiv2/exiv2#2359] opened 2022-09-17 14:48 UTC
#### **Describe the bug**
A clear and concise description of the bug, including your use case for exiv2.

Hello, I just download 0.27.5 binary from https://exiv2.org/download.html, my goal is to use it to extract exif info on My Mac app, but I got error "std::auto_ptr is not declare" when I compiled it. 

After checking source code, I found the header files on github are difference with downloaded package, all header files on github had changed  std::auto_ptr to std::unique_ptr, and it is correct since std::auto_ptr is deprecated after c++ 11.

I want know why there are two version header files, and do you have plan to update std::auto_ptr to std::unique_ptr with new version? 

Many thanks

#### **To Reproduce**
1. Provide the file with which you observed the issue (commonly named PoC). Explain the status of the file (e.g., direct from camera, edited with darktable), whether you own the copyright and if you allow the file to be added to exiv2 under the [project's license](https://github.com/Exiv2/exiv2/blob/main/COPYING)
2. List the exact commands/functions to reproduce the issue and include any related output
3. Mention the branch and commit in which you observed the issue (e.g., `main, commit 9f721b40`, `0.27-maintenance, latest`)

#### **Expected behavior**
A short description of what you expected to happen.

#### **Desktop (please complete the following information):**
- OS and version: (e.g., Linux (Fedora 36), macOS 12.5, Windows 11) macOS 12.4
- Exiv2 version and source: (e.g., 0.27.5 from exiv2.org) 0.27.5
- Compiler and version: (e.g., Gcc 12.2, Clang 14.0.0, MSVC 2022) Clang
- Compilation mode and/or compiler flags: (e.g., debug, `-O3`)

#### **Additional context**
Add any other information about the problem here.

**Comment by piponazo** [comment] 2022-09-17 15:44
Hi @yangpenglove . You already found out that there is a difference between the 0.27.5 release and the version we keep in the `main` branch. We keep releasing 0.27.X versions from time to time to fix bugs, but that branch is not anymore under active development. The code there is using the C++ 03 standard and not using any feature from modern C++. 

The active development is happening in the `main` branch where we started to migrate some code modern C++. You can download nightly releases of the newest branch from this page:
https://github.com/Exiv2/exiv2/releases

I am closing this ticket since it was a question (and not a bug).

**Closed by piponazo** 2022-09-17 15:44 UTC
Labels: bug

**Comment by yangpenglove** [comment] 2022-09-18 05:46
Thanks @piponazo.
May I know when will you release 1.0 version officially, and do you have plan to release arm64 arch since there will be more and more M1/M2 chip on macbook？

**Comment by piponazo** [comment] 2022-09-18 14:47
There is not a official plan (or at least I do not know about it, I have been a bit away from the project during the last months). Regarding the arm64 release, I think it should not be very challenging to add a new target in our CI pipelines. I am sure that if you open a ticket about it, somebody will tackle the task at some point.
