### ISSUE TITLE
Problems creating XMP files

### ISSUE THREAD

**Issue by Athesis** [Exiv2/exiv2#770] opened 2019-04-02 18:36 UTC
I try to create some XMP Data with Exiv2 (Version 0.27.0 - Build msvc64 libs), but failing. I created in Visual Studio 2017 an short test, based on the example at http://www.exiv2.org/doc/xmpsample_8cpp-example.html 

``` C++
#include "pch.h"

#include <exiv2/exiv2.hpp>

#include <string>
#include <iostream>

int main()
{
    try {

        Exiv2::XmpData xmpData;
        xmpData["Xmp.dc.source"] = "xmpsample.cpp";    // a simple text value
        xmpData["Xmp.dc.subject"] = "Palmtree";         // an array item
    }
    catch (Exiv2::AnyError& e) {
        std::cout << "Caught Exiv2 exception '" << e << "'\n";
        return -1;
    }
}
```

... but this fails with

>     Caught Exiv2 exception 'Invalid key '

If I try to add Exiv2::XmpProperties::registerNs("http://purl.org/dc/elements/1.1/", "dc"); the program fails with an

>     std::bad alloc

exception at this line

I just don't see what I'm doing wrong here?

**Comment by D4N** [comment] 2019-04-02 19:25
> I just don't see what I'm doing wrong here?

Neither do I, because the above code works for me on Linux. 

Could you run it with dr.memory or step through with a debugger to find out what actually throws the exception?

My guess is that something went wrong during linking of exiv2 (the xmpsdk is always linked statically, thus I'd suggest to also link libexiv2 statically).

> If I try to add Exiv2::XmpProperties::registerNs("http://purl.org/dc/elements/1.1/", "dc"); the program fails with an

I also don't get an exception here, although LeakSanitizer complains about a memory leak. That shouldn't happen.

**Comment by clanmills** [comment] 2019-04-10 10:21
I can't reproduce this with either v0.27 or v0.27.1 RC1 msvc build available from:  https://exiv2.org/download.html

```
C:\temp\foo\exiv2-0.27.1.1-msvc64>type 770.cpp
#include <exiv2/exiv2.hpp>
#include <string>
#include <iostream>
int main()
{
    try {
        Exiv2::XmpData xmpData;
        xmpData["Xmp.dc.source"] = "xmpsample.cpp";    // a simple text value
        xmpData["Xmp.dc.subject"] = "Palmtree";         // an array item

        std::string xmpPacket;
        Exiv2::XmpParser::encode(xmpPacket, xmpData);
        std::cout << xmpPacket << std::endl;
    } catch (Exiv2::AnyError& e) {
        std::cout << "Caught Exiv2 exception '" << e << "'\n";
        return -1;
    }
}

C:\temp\foo\exiv2-0.27.1.1-msvc64>cl /EHsc -Iinclude /MD 770.cpp /link lib\exiv2.lib lib\exiv2-xmp.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

770.cpp
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:770.exe
lib\exiv2.lib
lib\exiv2-xmp.lib
770.obj

C:\temp\foo\exiv2-0.27.1.1-msvc64>770
<?xpacket begin="∩╗┐" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:dc="http://purl.org/dc/elements/1.1/"
   dc:source="xmpsample.cpp">
   <dc:subject>
    <rdf:Bag>
     <rdf:li>Palmtree</rdf:li>
    </rdf:Bag>
   </dc:subject>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
.... blanks (deleted) .....
<?xpacket end="w"?>

C:\temp\foo\exiv2-0.27.1.1-msvc64>
```
The 0.27 behaviour is the same.  However, we changed the filename of the static xmp lib in 0.27.1
```
C:\temp>dir exiv2-0.27.0-msvc64\lib
 Volume in drive C has no label.
 Volume Serial Number is 0899-EF40

 Directory of C:\temp\exiv2-0.27.0-msvc64\lib

2019-04-10  10:43    <DIR>          .
2019-04-10  10:43    <DIR>          ..
2019-04-10  10:43         2,545,890 exiv2.lib
2019-04-10  10:43    <DIR>          pkgconfig
2019-04-10  10:43         2,121,874 xmp.lib <---
               2 File(s)      4,667,764 bytes
               3 Dir(s)   3,494,182,912 bytes free

C:\temp>dir exiv2-0.27.1.1-msvc64\lib
 Volume in drive C has no label.
 Volume Serial Number is 0899-EF40

 Directory of C:\temp\exiv2-0.27.1.1-msvc64\lib

2019-03-29  14:21    <DIR>          .
2019-03-29  14:21    <DIR>          ..
2019-03-29  14:21    <DIR>          exiv2
2019-03-29  14:11         2,123,112 exiv2-xmp.lib  <---
2019-03-29  14:20         2,546,268 exiv2.lib
2019-03-29  14:21    <DIR>          pkgconfig
               2 File(s)      4,669,380 bytes
               4 Dir(s)   3,494,182,912 bytes free

C:\temp>
```

It shouldn't be necessary to register the namespace as it is "pre-registered".  You can see the pregistered namespaces with the command `> exiv2 -vV --grep xml` or (using exifprint):
```
C:\temp\exiv2-0.27.1.1-msvc64>exifprint.exe --version | grep dc
xmlns=dc:http://purl.org/dc/elements/1.1/
xmlns=dcterms:http://purl.org/dc/terms/

C:\temp\exiv2-0.27.1.1-msvc64>
```

However registering again, should be harmless.

@D4N's suggestion about static/dynamic linking is plausible.  Indeed the xmp library (lib\xmp.lib or lib\exiv2-xmp.lib) is a static library.  When I link samples\exifprint.cpp using the instructions in ReadMe.txt in the bundle, it links the static xmp library and exiv2.dll

```
C:\temp\exiv2-0.27.1.1-msvc64>exifprint.exe --version | grep exiv
exiv2=0.27.0
processpath=C:\temp\exiv2-0.27.1.1-msvc64
package_name=exiv2
executable=C:\temp\exiv2-0.27.1.1-msvc64\exifprint.exe
library=C:\temp\exiv2-0.27.0-msvc64\bin\exiv2.dll
config_path=C:\Users\rmills\exiv2.ini

C:\temp\exiv2-0.27.1.1-msvc64>
```

There is a multi-threading issue in the code with respect to XMP as it must be initialised before starting threads.  However, as your code is not multi-threaded, I don't believe this is your issue.  https://dev.exiv2.org/projects/exiv2/wiki/Thread_safety

**Comment by clanmills** [comment] 2019-04-10 11:03
I've investigate the (unlikely) possibility that XMPsdk and/or your namespace has not been initialised.  It's good on v0.27 and v0.27.1 RC1.
```
C:\temp\exiv2-0.27.1.1-msvc64>type 770.cpp
#include <exiv2/exiv2.hpp>

#include <string>
#include <iostream>

int main()
{
    try {
        std::string prefix = "dc";
        std::string ns     = Exiv2::XmpProperties::ns(prefix) ;
        std::cout << prefix
                  << " => "
                  << ns
                  << std::endl;
if ( 0 ) {
        Exiv2::XmpData xmpData;
        xmpData["Xmp.dc.source"] = "xmpsample.cpp";    // a simple text value
        xmpData["Xmp.dc.subject"] = "Palmtree";         // an array item

        std::string xmpPacket;
        Exiv2::XmpParser::encode(xmpPacket, xmpData);
        std::cout << xmpPacket << std::endl;
}

    } catch (Exiv2::AnyError& e) {
        std::cout << "Caught Exiv2 exception '" << e << "'\n";
        return -1;
    }
}

C:\temp\exiv2-0.27.1.1-msvc64>cl /EHsc -Iinclude /MD 770.cpp /link lib\exiv2.lib lib\exiv2-xmp.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

770.cpp
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:770.exe
lib\exiv2.lib
lib\exiv2-xmp.lib
770.obj

C:\temp\exiv2-0.27.1.1-msvc64>770.exe
dc => http://purl.org/dc/elements/1.1/

C:\temp\exiv2-0.27.1.1-msvc64>
```

**Comment by Athesis** [comment] 2019-04-14 11:36
Hi,

Thankyou @clanmills for your Help and Support! I've should have tried an Release-Build earlier. It seems to be the difference of Debug to Release-Build ... With the release Build working great!

So far I never expirienced problems linking release-builds into a debug build of my own programmcode ... sure, I can't debug into the librarys in this case, but never had something straight up not working. Is there anything I could have missed? 

I Attached my Project-File here: 
[exiv2test.zip](https://github.com/Exiv2/exiv2/files/3077300/exiv2test.zip)

Thankyou!

**Comment by clanmills** [comment] 2019-04-15 22:26
Thanks for sending your sln/project files.  They look OK.  I see you have 32bit configurations which may may have selected for debug.  I'm sure you didn't - however that would explain why debug doesn't work!
  
Maybe you have to build and link the debug library with your debug application.  I wouldn't expect that.  I believe you can link and run a "release" library with a "debug" application.  

I see you've put the exiv2 build into F:\dev\LIB\Exiv2.  I'll have to change those settings on my machine.  I'll spend time on this tomorrow (Tuesday) and give you an update.

**Comment by clanmills** [comment] 2019-04-16 10:07
I've built and linked a debug library with your code.  It's working on both Release and Debug.  You'll need to link a Debug library build with your debug code.

I made a .tar.gz of the whole build and it's a whopping 145mb.  It's easier for you to re-walk my steps.  I didn't use 'f:\dev\LIB', instead I put exiv2-0.27.1.msvc64 into exiv2test\exiv2test directory and got release to build.  I added a "post build" step to `copy/y exiv2test\exiv2test\exiv2-0.27.1.msvc64\bin\*.dll $(TargetDir)`

I was rather surprised to reproduce `Invalid Key` on the Debug build.

I built exiv2 debug using the instructions in README-CONAN.md and copied the build directory into your project tree `copy/yesihq build/* exiv2test\exiv2test\exiv2-0.27.1-msvc64\Debug`  I modified the post-build step and linker to respect exiv2test\exiv2test\exiv2-0.27.1-msvc64\$(Configuration)\lib and exiv2test\exiv2test\exiv2-0.27.1-msvc64\$(Configuration)\bin

There's a little "gotcha" as we build the libraries into `build\$(Configuration)\lib`, however the dlls (and executables) are in `build\bin`.  For consistency, perhaps we should build them into `bin\$(Configuration)`.  I fixed the build tree manually (with a move or rename command, I don't remember exactly).

I got the debugging version to work.  I also used the debugger to step into library code from your code.

Final step was to give similar treatment to the Release to as Debug.  I created  `exiv2test\exiv2test\exiv2-0.27.1-msvc64\Release\` and moved exiv2test\exiv2test\exiv2-0.27.1-msvc64\bin and `exiv2test\exiv2test\exiv2-0.27.1-msvc64\lib` 

The compiler uses the same include directory for both Release and Debug: `exiv2test\exiv2test\exiv2-0.27.1-msvc64\include`

I'm going to close this issue as I believe this is solved.  Please don't start a discussion about "Why does Visual Studio behave in this way?" because I don't know and don't want to spend more time to investigate.

Thank You for using Exiv2.  Best Wishes in your project.

**Closed** 2019-04-16 10:08 UTC
Labels: Not-reproducible
