### ISSUE TITLE
Exiv 0.27 : broken API with ExifTags::groupList()

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#465] opened 2018-10-07 10:01 UTC
With new API 0.27, the ExifTags::groupList() disappears.

In digiKam we use this list to build a tags view categorized by group name. 

Code is here for example : 
 
https://cgit.kde.org/digikam.git/tree/core/libs/dmetadata/metaengine_exif.cpp#n1077
https://cgit.kde.org/digikam.git/tree/core/libs/dmetadata/metaengine_exif.cpp#n1138

Best

**Comment by piponazo** [comment] 2018-10-10 11:55
It seems that it was me who removed those functions recently in this commit while trying to hide implementation details (commit 6e4404d). This was done in the context of #450 .

I think we could easily add back those two functions to the API without too much effort. I do not remember exactly why I removed them from the API, but maybe I thought that those functions where not used at all in our code-base and I did not considered that they could be used in external projects.

If you agree with adding those functions back, I can take care of it.

**Comment by cgilles** [comment] 2018-10-10 12:14
yes, please restore the previous API.

In fact to be more clear, in digiKam, we have a tags filter list-view . To
setup the tags to show in this list, we need to know all Exif tags
(Makernotes includes) declared internally by Exiv2.

So in the GUI, we have a tags list editor where the user turn on the right
list to show.

This is exactly the same for IPTC and XMP, where API exists and still here
for 0.27. So the API needs to be homogeneous.

Note : we have 2 setup view about Exif : the standard tags and the
makernotes. Be aware to restore both access to internal tags list, and not
only standard Exif tags.

Gilles Caulier

Le mer. 10 oct. 2018 à 13:55, Luis Díaz Más <notifications@github.com> a
écrit :

**Comment by clanmills** [comment] 2018-10-10 19:14
@piponazo I've updated samples/taglist.cpp on my local copy of Exiv2 v0.26 as shown below.

It compiles and runs on Exiv2 v0.26.  You can run this (as before) with:
```
$ bin/taglist -> puts out loads of information about tags
$ bin/taglist --help (usage information)
$ bin/taglist Exif -> puts out the information about Exif tags
etc...
```
I've added two new features:
```
$ bin/taglist Groups -> enumerates the names of groups (Canon, Nikon1 etc)
$ bin/taglist --group Canon -> enumerate the tags in the group
```
--------------

When I use master, I see your changes to tags.hpp etc. Remarkably I cannot compile:
```
/Users/rmills/gnu/github/exiv2/exiv2/samples/taglist.cpp:51:52: error: no member named 'groupList' in 'Exiv2::ExifTags'
            const GroupInfo* groupList = ExifTags::groupList();
```
The declaration in include/exiv2/tags.hpp looks fine to me (and identical to v0.26) !!

Anyway, here's the code.  I'm sure we'll get this fixed on Thursday.

```
// ***************************************************************** -*- C++ -*-
/*
  Abstract:  Print a simple comma separated list of tags defined in Exiv2

  File:      taglist.cpp
  Author(s): Andreas Huggel (ahu) <ahuggel@gmx.net>
  History:   07-Jan-04, ahu: created
 */
// *****************************************************************************

#include <exiv2/exiv2.hpp>

#include <string>
#include <iostream>

using namespace Exiv2;

int main(int argc, char* argv[])
try {
    int rc = 0;

    switch (argc) {
    case 2:
    {
        std::string item(argv[1]);

        if (item == "Groups") {
 /*
 https://cgit.kde.org/digikam.git/tree/core/libs/dmetadata/metaengine_exif.cpp#n1077
        const Exiv2::GroupInfo* gi = Exiv2::ExifTags::groupList();

        while (gi->tagList_ != 0)
        {
            // NOTE: See BUG #375809 : MPF tags = exception Exiv2 0.26

            if (QLatin1String(gi->ifdName_) != QLatin1String("Makernote"))
            {
                Exiv2::TagListFct tl     = gi->tagList_;
                const Exiv2::TagInfo* ti = tl();

                while (ti->tag_ != 0xFFFF)
                {
                    tags << ti;
                    ++ti;
                }
            }

            ++gi;
        }
*/
            const GroupInfo* groupList = ExifTags::groupList();
            int count = 0;
            if ( groupList ) {
                while ( groupList->tagList_ && count < 10000 ) {
                    count ++ ;
                    std::cout << groupList->groupName_ << std::endl;
                    groupList++;
                }
            }
            std::cout << "Groups = " << count << std::endl;
            break;
        }

        if (item == "Exif") {
            ExifTags::taglist(std::cout);
            break;
        }

        if (item == "Iptc") {
            IptcDataSets::dataSetList(std::cout);
            break;
        }

        if (ExifTags::isExifGroup(item) || ExifTags::isMakerGroup(item)) {
            ExifTags::taglist(std::cout, item);
            break;
        }

        try {
            XmpProperties::printProperties(std::cout, item);
        }
        catch(const AnyError&) {
            rc = 2;
        }

        break;
    }
    case 1:
        ExifTags::taglist(std::cout);
    break;

    case 3:
    {
        rc = 1 ; // assume unhappy ending!
        std::string item(argv[1]);
        std::string name(argv[2]);

        if (item == "--group") {
            const GroupInfo* groupList = ExifTags::groupList();
            if ( groupList ) {
                while ( groupList->tagList_ ) {
                    int count = 0 ;
                    if ( name == groupList->groupName_ ) {
                        const Exiv2::TagInfo* tagInfo = groupList->tagList_();
                        while (tagInfo->tag_ != 0xFFFF)
                        {
                            std::cout << tagInfo->name_ << std::endl;
                            tagInfo++;
                            count++;
                        }
                        rc = 0 ;  // result is good
                        std::cout << "Tags = " << count << std::endl;
                    }
                    groupList++;
                }
            }
        }
    }
    break;

    default:
        rc = 1;
        break;
    }

    if (rc) {
        std::cout << "Usage: " << argv[0]
                  << " [--group name|Groups|Exif|Canon|CanonCs|CanonSi|CanonCf|Fujifilm|Minolta|Nikon1|Nikon2|Nikon3|Olympus|Panasonic|Pentax|Sigma|Sony|Iptc"
                  <<  "|dc|xmp|xmpRights|xmpMM|xmpBJ|xmpTPg|xmpDM|pdf|photoshop|crs|tiff|exif|aux|iptc]\n"
                  << "Print Exif tags, MakerNote tags, or Iptc datasets\n";
    }
    return rc;
}
catch (AnyError& e) {
    std::cout << "Caught Exiv2 exception '" << e << "'\n";
    return 1;
}
```

**Comment by cgilles** [comment] 2018-10-11 14:05
Confirmed. I recompiled Exiv2 from git/master today, and digiKam compile
fine using older ExifTags API.

https://commits.kde.org/digikam/7e0616df64673f9b57d58c672d7720a84f61b55e

Gilles Caulier

Le mer. 10 oct. 2018 à 21:14, Robin Mills <notifications@github.com> a
écrit :

**Comment by piponazo** [comment] 2018-10-11 14:36
Great! I'll close this issue then.

**Comment by clanmills** [comment] 2018-10-11 18:37
The compilation issue with samples/taglist.cpp is on MacOS-X (Xcode 10.0).  It's OK on Linux and MinGW.  I think it's ok on Cygwin and MSVC.
```
/Users/rmills/gnu/github/exiv2/exiv2/samples/taglist.cpp:51:52: error: no member named 'groupList' in 'Exiv2::ExifTags'
            const GroupInfo* groupList = ExifTags::groupList();
```

**Comment by clanmills** [comment] 2018-10-11 20:17
This is extraordinary.  For sure it's a compiler issue.  The entry point is in the library:
```
623 rmills@rmillsmm:~/gnu/github/exiv2/master/build $ nm --demangle lib/libexiv2.0.27.0.0.dylib | grep groupList
00000000001217f0 T Exiv2::ExifTags::groupList()
00000000002376a0 t Exiv2::Internal::groupList()
624 rmills@rmillsmm:~/gnu/github/exiv2/master/build $ 
```
I generated an Xcode project and loaded the file into the editor. The "autocomplete" in Xcode doesn't know about the entry point, although he offers `isMakerGroup` and `isExifGroup` which are declared a few lines later in include/exiv2/tags.hpp  The "autocomplete" will use clang to read the code, so this doesn't say anything new.

I've also wondered if he's confused by Internal::groupList() and ExifTags::groupList(), so I modified Internal to be groupListInternal().  That didn't fix it either.

```
619 rmills@rmillsmm:~/gnu/github/exiv2/master $ finder "*pp" $G -H isExifGroup $___
./include/exiv2/tags.hpp:        static bool isExifGroup(const std::string& groupName);
./samples/taglist.cpp:                if (ExifTags::isExifGroup(item) || ExifTags::isMakerGroup(item)) {
./src/tags.cpp:    bool ExifTags::isExifGroup(const std::string& groupName)
620 rmills@rmillsmm:~/gnu/github/exiv2/master $ finder "*pp" $G -H groupList $___
./include/exiv2/tags.hpp:        static const GroupInfo* groupList();
./samples/taglist.cpp:                           const Exiv2::GroupInfo* gi = Exiv2::ExifTags::groupList();
./samples/taglist.cpp:                    const GroupInfo* groupList = ExifTags::groupList();
./samples/taglist.cpp:                    if (groupList) {
./samples/taglist.cpp:                        while (groupList->tagList_ && count < 10000) {
./samples/taglist.cpp:                            std::cout << groupList->groupName_ << std::endl;
./samples/taglist.cpp:                            groupList++;
./samples/taglist.cpp:                    const GroupInfo* groupList = ExifTags::groupList();
./samples/taglist.cpp:                    if (groupList) {
./samples/taglist.cpp:                        while (groupList->tagList_) {
./samples/taglist.cpp:                            if (name == groupList->groupName_) {
./samples/taglist.cpp:                                const Exiv2::TagInfo* tagInfo = groupList->tagList_();
./samples/taglist.cpp:                            groupList++;
./src/tags_int.cpp:    const GroupInfo *groupList()
./src/tags.cpp:    const GroupInfo *ExifTags::groupList()
./src/tags.cpp:        return Internal::groupList();
./src/tags_int.hpp:    const GroupInfo* groupList();
621 rmills@rmillsmm:~/gnu/github/exiv2/master $ 
```

Another long frustrating day.  However, I feel we're making steady progress.  For sure, I really miss having Jenkins to do all the builds and keep me aware of cross-platform issues.

@piponazo Is this only on my machine?  Did Travis build 'master' OK on MacOS-X?

**Comment by piponazo** [comment] 2018-10-12 06:06
I suspect this is only happening in your machine. Every time we create a PR, the changes are tested over all the platforms. One of them is XCode9, and it is passing the tests on master:

https://travis-ci.org/Exiv2/exiv2/jobs/440348345

**Comment by clanmills** [comment] 2018-10-12 10:05
It's building OK on Yosemite with Xcode 7.0.  I see Apple have an RC for Xcode 10.1.  I'll try that.  If that doesn't fix it, I'll report this on Radar (Apple's bug tracking system). 

The code in v0.26 compiles OK with Xcode 10.0, so there is a way to get the code to compile on Xcode 10.0.  However, I'm not going to spend the time to discover how.

**Comment by clanmills** [comment] 2018-10-12 11:38
It builds OK with Xcode 9.4.  Xcode 10.1beta has the same compiler as 10.0 and doesn't build.  I'll report this to Apple and install 9.4 on my machines.   Closing this now.

**Comment by clanmills** [comment] 2018-10-12 12:15
https://bugreport.apple.com/web/?problemID=45223696

**Comment by clanmills** [comment] 2018-11-07 15:36
I documented the issue in releasenotes/releasenotes.txt for v0.27 RC1

I've had a response from Apple.  I think they are saying "Can't reproduce".  I'll install a fresh MacOS-X VM with Xcode 10 and try again.  

_Engineering has requested the following information in order to further investigate this issue:_

_Can you please tell at what revision the problem should be reproducible? It looks like there were changes made to work around the problem, so, maybe that’s why it’s not reproducible anymore. In our testing revisions 12d44f8f17bb541d5ce0c05e6020bc5d79a03e34 and afc1a1e5263e894360f80d9316e00d7668760079 were built successfully and resulting ./bin/taglist runs without crashing._

**Comment by piponazo** [comment] 2018-11-07 15:47
@clanmills I think it would be a better idea to create a new issue about the topic you are investigating. The original title of this issue is "broken API with ExifTags::groupList()" and that problem was solved.

**Comment by clanmills** [comment] 2018-11-07 15:55
@piponazo You are right.  I was thinking that "we can only compile that API with Xcode 9.4".  Nope, that's not right.  There are two different matters:

1) We lost the API and that's the original subject of this issue.
2) Xcode 10 cannot compile `samples/taglist.cpp` 

I'll close this and open a new issue concerning Xcode 10 and the correspondence with Apple.

**Closed by clanmills** 2018-11-07 15:55 UTC
