### ISSUE TITLE
exiv2 crashes when trying to read xmp metadata made by darktable software

### ISSUE THREAD

**Issue by Aceler** [Exiv2/exiv2#2014] opened 2021-12-02 12:00 UTC
Maybe the XMP data from darktable is corrupt, but exiv2 shouldn't crash anyways.

##### **To Reproduce**
Export a jpg file from Darktable software. Open it up in exiv2.

$ exiv2 -p x pr 0002.jpg 
Xmp.crd.CameraProfile                        XmpText    12  Camera Vivid
Xmp.crd.ColorNoiseReduction                  XmpText     1  7
Xmp.crd.ColorNoiseReductionDetail            XmpText     2  50
Xmp.crd.ColorNoiseReductionSmoothness        XmpText     2  50
Xmp.crd.Contrast2012                         XmpText     1  0
Xmp.crd.Exposure2012                         XmpText     4  0.00
Xmp.crd.Highlights2012                       XmpText     1  0
Xmp.crd.LuminanceNoiseReductionContrast      XmpText     1  0
Xmp.crd.LuminanceNoiseReductionDetail        XmpText     2  75
Xmp.crd.LuminanceSmoothing                   XmpText     1  3
Xmp.crd.Saturation                           XmpText     1  0
Xmp.crd.Shadows2012                          XmpText     1  0
Xmp.crd.SharpenDetail                        XmpText     2  25
Xmp.crd.SharpenEdgeMasking                   XmpText     1  0
Xmp.crd.SharpenRadius                        XmpText     4  2.00
Xmp.crd.Sharpness                            XmpText     2  56
Xmp.exif.DateTimeOriginal                    XmpText    19  Uncaught exception: basic_string::at: __n (which is 19) >= this->size() (which is 19)

$ exiv2 -V
exiv2 0.27.2

##### **Desktop (please complete the following information):**
- OS and version: Ubuntu 20.04

##### **Additional context**
This also cause gthumb, gwenview and other viewers to crash. See https://bugs.launchpad.net/ubuntu/+source/gthumb/+bug/1943586

Test image attached here:
![0002](https://user-images.githubusercontent.com/5177608/144418129-4aa0e02d-8471-4c1b-a034-246f51b50969.jpg)

**Comment by kmilos** [comment] 2021-12-02 13:46
Thanks for the report, but a duplicate of https://github.com/Exiv2/exiv2/issues/2011, please search before opening new issues.

Already fixed by exiv2, it is up to packagers to update or backport.

**Closed** 2021-12-02 13:46 UTC
Labels: bug

**Comment by clanmills** [comment] 2021-12-02 18:18
Beautiful test image.  Is the location Switzerland or Canada?

**Comment by Aceler** [comment] 2021-12-02 18:27
@kmilos ah, yes, I searched only for open reports, my bad. I'm sorry.

@clanmills It is Tolyatti, Russia.
