### ISSUE TITLE
Arm64 for Apple silicon

### ISSUE THREAD

**Issue by yangpenglove** [Exiv2/exiv2#2360] opened 2022-09-18 15:10 UTC
#### **Is your feature request related to a problem?**

There are more and more mac computer will use M chip, but the nightly build still only has x86_64 arch, could you please add universal binary which includes both x86_64 and arm64?

Thanks

**Comment by postscript-dev** [comment] 2022-09-19 09:36
@yangpenglove:
> There are more and more mac computer will use M chip, but the nightly build still only has x86_64 arch, could you please add universal binary which includes both x86_64 and arm64?

When investigating support for Apple M chips, we found that there was no [GitHub CI support](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). It is possible to cross build for Apple chips but we would not be able to run any tests to check that everything was working correctly. When GitHub adds support then someone can make the changes in Exiv2.


In #2173, another user requested adding support for Apple M chips. In there, there is a discussion on building Exiv2 from source that you may find helpful.

I am closing this issue as it is a duplicate of #2173.

**Closed by postscript-dev** 2022-09-19 09:36 UTC
Labels: CI, request, build, good first issue

**Comment by kmilos** [comment] 2022-09-19 10:31
AFAIK, [exiv2 0.27.5 is available from MacPorts for arm64](https://ports.macports.org/port/exiv2/details/), don't know about Homebrew...

**Comment by 1div0** [comment] 2022-09-20 06:22
Also, w/ BMFF enabled.

https://github.com/Homebrew/homebrew-core/blob/1a0fc22bf98b372d71a8a137d285f5764375a547/Formula/exiv2.rb#L45

**Comment by gvellut** [comment] 2023-10-19 11:18
> When investigating support for Apple M chips, we found that there was no [GitHub CI support](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

There is now a runner for M1 actions: 
- https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ .
- https://github.com/actions/runner-images/issues/8439

(but it is not free for now)

**Comment by kgantchev** [comment] 2024-01-15 16:44
> (but it is not free for now)


You can use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)
