### ISSUE TITLE
Lens Canon EF-S 17-85mm f/4-5.6 IS USM is not recognised

### ISSUE THREAD

**Issue by eezacque** [Exiv2/exiv2#2010] opened 2021-11-29 20:09 UTC
##### **Describe the bug**
Lens Canon EF-S 17-85mm f/4-5.6 IS USM is not recognised

##### **To Reproduce**
$ exiv2 -pt IMG_8303_CR2_embedded.jpg | grep -ai lens
Exif.CanonCs.LensType                        Short       1  n/a
Exif.CanonCs.Lens                            Short       3  17.0 - 85.0 mm
Exif.CanonCf.LensAFStopButton                Short       1  2048

##### **Expected behavior**
Instead of "n/a" I expect to see "Canon EF-S 17-85mm f/4-5.6 IS USM"

##### **Desktop (please complete the following information):**
Running Ubuntu 20.04.3 LTS

![IMG_8303_CR2_embedded](https://user-images.githubusercontent.com/37875990/143935127-1968920e-6125-4b1d-a6ea-1757b774aeb7.jpg)

**Comment by hassec** [comment] 2021-11-30 08:39
@eezacque I've confirmed this issue on master but checking `exiv2 -pv` shows the following raw values that don't make sense:

```
0x0016 CanonCs      LensType                    Short       1  65535
0x001a CanonCs      MaxAperture                 Short       1  65535
0x001b CanonCs      MinAperture                 Short       1  65535
```

Thus, I'm tempted to think that there is an issue with the file itself. How was the `*.jpg` file produced? Do you still have the raw file?

**Comment by eezacque** [comment] 2021-11-30 09:41
The original raw has the same issue, with additional warning:
```
$ exiv2 -pt IMG_8303.CR2 | grep -ai lens
Warning: Directory Canon has an unexpected next pointer; ignored.
Exif.CanonCs.LensType                        Short       1  n/a
Exif.CanonCs.Lens                            Short       3  17.0 - 85.0 mm
Exif.CanonCf.LensAFStopButton                Short       1  2048
```

**Comment by hassec** [comment] 2021-11-30 10:51
@eezacque can you check what `exiftool` reports on your raw file?    
On the JPG I get the same problem of `LensType = 65535` with exiftool.

**Comment by clanmills** [comment] 2021-11-30 11:39
I think this is a "manual lens".  There is no metadata concerning the lens.  I'm not a photographer, however I think is for legacy lenses with no digital interface to the camera.

**Comment by eezacque** [comment] 2021-11-30 11:55
This is no 'manual lens': [https://www.usa.canon.com/internet/portal/us/home/products/details/lenses/ef/standard-zoom/ef-s-17-85mm-f-4-5-6-is-usm](url).  Please note that this lens is included in the source code, it just isn't correctly referenced to the exif. I believe this is a bug.

**Comment by clanmills** [comment] 2021-11-30 11:57
There is no useful metadata in the image.  It's not a bug.  Exiv2 is correctly reporting the metadata.  The exiftool output says the same thing.

**Comment by eezacque** [comment] 2021-12-09 17:28
I contacted Canon on this, and they maintain that a Canon 350D does write its lens metadata to exif version 2.21, and that any software that does not report  lens data must be incompatible with exif 2.21. If the lens data is really missing, my camera must be broken, and it should produce all black pictures, according to Canon. Looks like Canon customer support went tits up in the last decade or so...

**Comment by clanmills** [comment] 2021-12-09 18:12
@eezacque I see you'd like to quarrel and I have no wish to allow that.

I have examined your file with the following software products:  exiv2, exiftool, Preview.app (macOS) ADCSee PhotoStudio7 and tvisitor (the code in my book).  None have identified your lens.

Four questions:
1. Can we agree that we are discussing the same file (which is attached to this report).  The image at 250k seems quite small.
```
717 rmills@rmillsm1:~/Desktop $ ls -l 143935127-1968920e-6125-4b1d-a6ea-1757b774aeb7.jpg 
-rw-r--r--@ 1 rmills  staff  258370  9 Dec 17:56 143935127-1968920e-6125-4b1d-a6ea-1757b774aeb7.jpg
718 rmills@rmillsm1:~/Desktop $ 
```
2. Has the image been post-processed or stripped in some way.  Did this image come directly from the camera.
3. Have you seen your lens metadata correctly identified using any software such as PhotoShop, a Microsoft Product, or on by a web-site metadata viewer?
4. Is there another possibility.  For example, if the camera is in 'manual mode', is the lens data missing?

**Comment by eezacque** [comment] 2021-12-13 12:26
I don't like to quarrel at all, I just want to learn what is going on here.

You can find the original raw at [https://eezacque.home.xs4all.nl/test.CR2](url). The jpg posted was created by shotwell, but it has the same symptoms as the raw. Photoshop shows the LensType tag missing too.

So far I have yet to see proof that the LensType tag is present in the EXIF, the only claim that it is there is from Canon, but they have failed to provide proof that an EOS 350D writes this tag.

**Comment by clanmills** [comment] 2021-12-13 14:35
I'm glad we're not quarrelling.  Can you answer any of my four questions?  And another question "Why are you concerned about this?"  I'm not a photographer, so I don't know the importance of recognising the lens type in an image.

You can use the "configuration file" ~/.exiv2 to provide the lens recognition as follows:

```
836 rmills@rmillsm1:~/Downloads $ exiv2 -pv -g lens/i test.CR2 
Warning: Directory Canon has an unexpected next pointer; ignored.
0x0016 CanonCs      LensType                    Short       1  65535  <--- This number
0x0017 CanonCs      Lens                        Short       3  85 17 1
0x0009 CanonCf      LensAFStopButton            Short       1  2048
837 rmills@rmillsm1:~/Downloads $ cat ~/.exiv2 
[canon]
65535=Canon EF-S 17-85mm f/4-5.6 IS USM  <--- identify it for exiv2
838 rmills@rmillsm1:~/Downloads $ exiv2 -g lens/i test.CR2 
Warning: Directory Canon has an unexpected next pointer; ignored.
Exif.CanonCs.LensType                        Short       1  Canon EF-S 17-85mm f/4-5.6 IS USM  <--- Et Voila!
Exif.CanonCs.Lens                            Short       3  17.0 - 85.0 mm
Exif.CanonCf.LensAFStopButton                Short       1  2048
839 rmills@rmillsm1:~/Downloads $ 
```

Thanks @hassec for those references.  I'll read them now.

**Comment by clanmills** [comment] 2021-12-13 14:52
Looking in the code, that is lens 234:
```bash
842 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ grep USM src/*.cpp | grep 85 | grep EF-S
src/canonmn_int.cpp:        {  234, "Canon EF-S 17-85mm f/4-5.6 IS USM"                         },
src/canonmn_int.cpp:        {  488, "Canon EF-S 15-85mm f/3.5-5.6 IS USM"                       },
843 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ 
```

So, let's modify the metadata:

```bash
845 rmills@rmillsm1:~/Downloads $ cp test.CR2 test.CR2.original
846 rmills@rmillsm1:~/Downloads $ exiv2 -g lens/i test.CR2
Warning: Directory Canon has an unexpected next pointer; ignored.
Exif.CanonCs.LensType                        Short       1  n/a
Exif.CanonCs.Lens                            Short       3  17.0 - 85.0 mm
Exif.CanonCf.LensAFStopButton                Short       1  2048
847 rmills@rmillsm1:~/Downloads $ exiv2 -M'set Exif.CanonCs.LensType 234' test.CR2
Warning: Directory Canon has an unexpected next pointer; ignored.
Warning: Directory Canon has an unexpected next pointer; ignored.
848 rmills@rmillsm1:~/Downloads $ exiv2 -g lens/i test.CR2
Warning: Directory Canon has an unexpected next pointer; ignored.
Exif.CanonCs.LensType                        Short       1  Canon EF-S 17-85mm f/4-5.6 IS USM
Exif.CanonCs.Lens                            Short       3  17.0 - 85.0 mm
Exif.CanonCf.LensAFStopButton                Short       1  2048
849 rmills@rmillsm1:~/Downloads $ exiftool test.CR2 | grep -i lens
Lens Type                       : Canon EF-S 17-85mm f/4-5.6 IS USM or Tokina Lens
Lens                            : 17.0 - 85.0 mm
Lens ID                         : Canon EF-S 17-85mm f/4-5.6 IS USM
Lens                            : 17.0 - 85.0 mm (35 mm equivalent: 27.6 - 137.9 mm)
850 rmills@rmillsm1:~/Downloads $ 
```

Pretty good, eh?  Two solutions.  And '234' fixes exiftool as well.

@hassec Thanks for those references.  The exiftool forum discussion is concerns a user command-line error.  The other discussion says blames the Sigma/Third-party lens.  I believe we're dealing with a bona-video Canon lens.

Let's hear from @eezacque so I understand exactly what we're discussing.  _(that's not sarcasm: I am really confused.)_

**Comment by eezacque** [comment] 2021-12-13 18:02
First of all, let me answer your four questions:
1. We are looking at the same file.
2. As stated above, the jpg is generated by shotwell.
3. As stated above, the lens type is not identified by Adobe Photoshop, either.
4. The camera is shooting in manual mode, but shooting in auto mode doesn't make a difference

Thanks for pointing out how to set the Lens Type tag, I already figured this out, but I appreciate your helpfulness.

What I'm trying to discuss is whether the problem is in Canon's firmware. It looks like this is the case.

**Comment by clanmills** [comment] 2021-12-13 18:48
Right.  Thanks for the reply.  Is there a problem with the Canon Firmware?  Only Canon can answer that, and I believe you get a reply from them.

The MakerNotes are a problem.  None of the manufacturers _(Canon, Sony, Nikon etc...)_ publish the layout of the data in their makernote.  It has been reverse engineered by the community.  The ExifTool documentation is the best available resource.

I don't know why why the Manufacturers do not publish their specs.  They will mumble excuses about resources, business priorities, the scattered nature of the Open Source Community and so on.  We had a major initiative in 2020/2021 to add support for CR3 to Exiv2 and darktable.   The Community asked Canon for assistance on the basis that Canon Customers have purchased Cameras and wanted to post-process their images with open-source products.  Canon _politely_ declined.

Unless you have a reason to keep this issue report open, I intend to close it.  There is no evidence that Exiv2 is defective concerning this lens.  In fact, it's the opposite.  There is strong evidence that Exiv2 is working correctly.  Additionally, your concerns have been carefully and thoughtfully investigated by @hassec and myself.  Other members of Team Exiv2 will be quietly observing this discussion.  Please remember that everybody in Team Exiv2 is a volunteer.  Unlike the support folks at Canon, Adobe and other businesses, we are not paid.  I believe we provide good service to users of Exiv2.

If you are corresponding with Canon again, perhaps you could ask them to publish the specification of their makernotes and proprietary raw formats CR3, CR2 and CRW.  It is very likely that Canon have an SDK which they share with Adobe and other businesses.   Maybe one day Canon will put that resource into the public domain.

**Closed by clanmills** 2021-12-13 18:48 UTC
Labels: wontfix, lens

**Comment by eezacque** [comment] 2021-12-13 19:06
Agreed.
