### ISSUE TITLE
Library version in SONAME goes backward

### ISSUE THREAD

**Issue by lantw44** [Exiv2/exiv2#507] opened 2018-11-01 13:34 UTC
Exiv2 0.26 has SONAME `libexiv2.so.26`, but Exiv2 0.27 has SONAME `libexiv2.so.0`. Is it expected? It looks wrong for the version number to go backward.

**Comment by clanmills** [comment] 2018-11-01 14:14
What is SONAME?

**Comment by clanmills** [comment] 2018-11-01 14:40
MinGW/msys2 32 bit builds `msys-exiv2-27.dll`

```
270 rmills@rmillsmm-w7-32:~/gnu/github/exiv2/exiv2/build $ git diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 30605c65..18af5d9d 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -204,7 +204,7 @@ endif()

 set_target_properties( exiv2lib PROPERTIES
     VERSION       ${PROJECT_VERSION}
-    SOVERSION     ${PROJECT_VERSION_MAJOR}
+    SOVERSION     ${PROJECT_VERSION_MINOR}
     OUTPUT_NAME   exiv2
     PDB_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
     COMPILE_FLAGS ${EXTRA_COMPILE_FLAGS}
271 rmills@rmillsmm-w7-32:~/gnu/github/exiv2/exiv2/build $ find . -name "*.dll"
./bin/msys-exiv2-0.dll  <--- old dll from yesterday
./bin/msys-exiv2-27.dll <--- nice new dll
272 rmills@rmillsmm-w7-32:~/gnu/github/exiv2/exiv2/build $
```

**Comment by piponazo** [comment] 2018-11-01 14:49
@lantw44 thanks for reporting this! You're are right, this have been a mistake in our cleaning up of the CMake code. I'll fix it today.

**Comment by lantw44** [comment] 2018-11-02 16:40
SONAME is correct now but there is a little inconsistency between file names of old and new versions:
```
libexiv2.so.26 -> libexiv2.so.26.0.0
libexiv2.so.27 -> libexiv2.so.0.27.0.1
```
Is it an expected change? Since SONAME is correct, this kind of different should be harmless on most ELF platforms.

**Comment by piponazo** [comment] 2018-11-04 21:55
We did not make this change intentionally, but it has been caused by a clean-up of the CMake code. I cleaned up few variables we were using that were related with the versioning, and now we just use the standard way that CMake provides to specify the project version:

https://cmake.org/cmake/help/v3.13/command/project.html

If this is harmless as you mentioned, I would keep the things as they are now. At some point in the future, we might reach the version 1.0, and then the SO files would like something like `libexiv2.so.1.0.1`.

**Comment by clanmills** [comment] 2018-11-04 22:29
I'm unhappy with this position, Luis.  We want to have quite different DLL names while the API is volatile.  When we arrive at Exiv2 v1.0, the DLL should have a "one" and all Exiv2 v1.0 libraries should offer the same API.

If we accept things as they stand and have v0.27 and v0.28 in circulation, both with have a "zero".

When I said we made the change _intentionally_, I should have said _knowingly_.

And/or perhaps we set MINOR to 100 when we arrive at Exiv2 1.0.

**Comment by piponazo** [comment] 2018-11-06 13:03
It was just my opinion, each one can have their own one 😉 . 

For me it is a minor detail, so I would accept whatever the majority prefers.

**Comment by clanmills** [comment] 2018-11-17 09:57
We've made progress with this for Exiv2 v0.27 RC2 on Windows (MSVC, CYGWIN, MinGW/msys2).  There could be outstanding issues on other platforms (MacOS and Linux).

On Windows, the DLLs are:
```
$ for d in *;do (cd $d ; find . -type f -name "*.dll" $L) ; done
-rwxr-xr-x+ 1 rmills staff 5598364 Nov 17 01:20 ./exiv2-0.27.0.2-CYGWIN/bin/cygexiv2-27.dll
-rwxr-xr-x+ 1 rmills staff 4895090 Nov 17 01:20 ./exiv2-0.27.0.2-MinGW32/bin/msys-exiv2-27.dll
-rwxr-xr-x+ 1 rmills staff 5513802 Nov 17 01:20 ./exiv2-0.27.0.2-MinGW64/bin/msys-exiv2-27.dll
-rw-rw-rw-+ 1 rmills staff 2314752 Nov 17 01:20 ./exiv2-0.27.0.2-MSVC/bin/exiv2.dll
```
That seems fine to me.  The DLLs are "versioned" on CYGWIN and MinGW/msys2.  The MSVC dll has always been called exiv2.dll for every version of Exiv2.

The shared objects on Linux and Darwin are:
```
$ for d in *;do (cd $d ; find . -type f -name "*.so.*" $L) ; done
-rw-r--r--+ 1 rmills staff 4557192 Nov 17 01:16 ./exiv2-0.27.0.2-Linux/lib/libexiv2.so.0.27.0.2
$ for d in *;do (cd $d ; find . -type f -name "*.dylib" $L) ; done
-rwxr-xr-x+ 1 rmills staff 5024184 Nov 17 01:16 ./exiv2-0.27.0.2-Darwin/lib/libexiv2.0.27.0.2.dylib
```

This works fine.  `$ sudo make install` sets up appropriate links:
```
$ for d in *;do (cd $d ; find . -type l -name "*.dylib" $L) ; done
lrwxr-xr-x 1 rmills staff 23 Nov 17 01:16 ./exiv2-0.27.0.2-Darwin/lib/libexiv2.27.dylib -> libexiv2.0.27.0.2.dylib
lrwxr-xr-x 1 rmills staff 17 Nov 17 01:16 ./exiv2-0.27.0.2-Darwin/lib/libexiv2.dylib -> libexiv2.27.dylib
$ for d in *;do (cd $d ; find . -type l -name "*.so.*" $L) ; done
lrwxr-xr-x 1 rmills staff 20 Nov 17 01:16 ./exiv2-0.27.0.2-Linux/lib/libexiv2.so.27 -> libexiv2.so.0.27.0.2
```

Next week, I will investigate what was done in Exiv2 v0.26 and report back here.  If we decide that another change is desirable, we can do that for RC3.

**Comment by clanmills** [comment] 2018-11-17 18:30
Here's what was released in Exiv2 0.26:
```
503 rmills@rmillsmbp:~/Downloads/0.26 $ finder "*.dll" | grep exiv2
./dist/2013/x64/dll/Release/bin/exiv2.dll
./dist/2013/Win32/dll/Release/bin/exiv2.dll
./dist/2015/x64/dll/Release/bin/exiv2.dll
./dist/2015/Win32/dll/Release/bin/exiv2.dll
./dist/2012/x64/dll/Release/bin/exiv2.dll
./dist/2012/Win32/dll/Release/bin/exiv2.dll
./dist/2008/x64/dll/Release/bin/exiv2.dll
./dist/2008/Win32/dll/Release/bin/exiv2.dll
./dist/2010/x64/dll/Release/bin/exiv2.dll
./dist/2010/Win32/dll/Release/bin/exiv2.dll
./dist/mingw/bin/libexiv2-26.dll
./dist/2005/x64/dll/Release/bin/exiv2.dll
./dist/2005/Win32/dll/Release/bin/exiv2.dll
./dist/cygwin/bin/cygexiv2-26.dll
504 rmills@rmillsmbp:~/Downloads/0.26 $ find . -name "*.so*" -type f | grep exiv2
./dist/linux/lib/libexiv2.so.26.0.0
505 rmills@rmillsmbp:~/Downloads/0.26 $ find . -name "*.so*" -type f $L | grep exiv2
-rw-r--r--@ 1 rmills  staff  5084028 17 May  2017 ./dist/linux/lib/libexiv2.so.26.0.0
506 rmills@rmillsmbp:~/Downloads/0.26 $ find . -name "*.dylib*" -type f $L | grep exiv2
-rwxr-xr-x@ 1 rmills  staff  5162180 17 May  2017 ./dist/macosx/lib/libexiv2.26.0.0.dylib
507 rmills@rmillsmbp:~/Downloads/0.26 $ 
```

So the comparison is:

| Platform | v0.26.0.0 | v0.27.0.2 (RC2) |
|:-----     |:------ |:-----  |
| CYGWIN | cygexiv2-26.dll | cygexiv2-27.dll |
| MinGW/msys/1.0 | libexiv2-26.dll |  |
| MinGW/msys2 |  | msys-exiv2-27.dll |
| MSVC  | exiv2.dll | exiv2.dll |
| Linux | libexiv2.so.26.0.0 | libexiv2.so.0.27.0.2 |
| MacOS-X | libexiv2.26.0.0.dylib | libexiv2.0.27.0.2.dylib |

I see that Linux and MacOS-X have morphed from libexiv2.so.26.0.0 to libexiv2.so.0.27.0.2.  Is this serious?  I personally prefer the _**v0.26**_ name.  I can live with the _**v0.27**_ name.

This issue will be closed on 2018-11-24 unless somebody puts forward a strong reason for change.

RC3 is 2018-12-07 after which only _**must fix**_ issues will serviced as we enter **v0.27 Code Freeze**.

**Comment by lantw44** [comment] 2018-11-18 04:58
> I see that Linux and MacOS-X have morphed from libexiv2.so.26.0.0 to libexiv2.so.0.27.0.2. Is this serious? I personally prefer the _**v0.26**_ name. I can live with the _**v0.27**_ name.

It should be fine on Linux and most *BSD as long as SONAME, which can be found with `readelf -d` command, is correct. The linker uses SONAME to find the library so there has to be a symbolic link with the name specified in SONAME (`libexiv2.so.27`) which points to the real library (`libexiv2.so.0.27.0.2`). 

I am not sure whether Exiv2 is going to bump the SONAME on every release. [ABI Tracker](https://abi-laboratory.pro/index.php?view=timeline&l=exiv2) says Exiv2 isn't binary compatible across releases, so I think the current way of synchronizing the SONAME with the version number is OK.

I don't know how macOS and OpenBSD linkers work, so I cannot know whether it will affect them. OpenBSD has a special linker which doesn't use SONAME and OpenBSD ports seems to have its own way to manage library name. For example, Exiv2 0.26 on OpenBSD 6.4 has file name `libexiv2.so.9.0` with no symbolic links.

**Comment by clanmills** [comment] 2018-11-18 07:58
Thank You very much for this very helpful input. And thank you for you work on RC1.  Your feedback is appreciated.  Here's what I see on Linux:
```
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/buildserver/build$ readelf -d lib/libexiv2.so.0.27.0.2  | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libexiv2.so.27]
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/buildserver/build$
```

We intend an unchanging API (and ABI) for Exiv2 v0.27 when we issue "dot" releases over the couple of years.

During the RC stage of exiv2 v0.26, I was surprised to realise that autotools and CMake were generating different filenames and "-compatibility_version" http://dev.exiv2.org/issues/1293.  I aligned them on 26.

I've never heard of SONAME until you mentioned it.  With Exiv2 v0.27,  we have discontinued our autotools support and msvc  solution/project files.  We have done this for many good reasons and expect that CMake will provide stronger integrity with platform conventions and standards.

I'm surprised by what you've said about OpenBSD using the filename libexiv2.so.9.0.  I hope by using CMake, such _almost hidden_ ABI issues have been solved.

Once more I'd like to express my appreciation for your feedback on RC1 concerning SONAME, pthreads and FreeBSD.  Yesterday I published RC2 on http://exiv2.dyndns.org and I welcome any comments you'd like to make.

**Comment by clanmills** [comment] 2018-11-18 08:21
Concerning MacOS-X, every library has a compatibility-version which is used by the dynamic linker to determine the release of the API offered by the library.
```
594 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ otool -L lib/libexiv2.dylib 
lib/libexiv2.dylib:
	@rpath/libexiv2.27.dylib (compatibility version 27.0.0, current version 0.27.0)
	/usr/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.2.0)
	/usr/local/lib/libexpat.1.dylib (compatibility version 8.0.0, current version 8.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
595 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ 
```

I don't believe that DLLs have anything explicit to say "this is version v0.27",  however any application linked to a "stub" library can only load a DLL which offers a compatible API.

**Comment by clanmills** [comment] 2018-11-20 13:11
Thanks everybody for discussing this.  A big "Thank You" to @lantw44 for opening this discussion.

I'm going to close this now as I believe we've dealt with this.

**Closed by clanmills** 2018-11-20 13:11 UTC
