### ISSUE TITLE
0.27.2: test suite build fails

### ISSUE THREAD

**Issue by kloczek** [Exiv2/exiv2#997] opened 2019-09-07 11:17 UTC
<pre>[ 48%] <font color="#4E9A06"><b>Linking CXX executable ../bin/unit_tests</b></font>
cd /home/tkloczko/rpmbuild/BUILD/exiv2-0.27.2/unitTests &amp;&amp; /usr/bin/cmake -E cmake_link_script CMakeFiles/unit_tests.dir/link.txt --verbose=1
/usr/bin/g++  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Wall -Wcast-align -Wpointer-arith -Wformat-security -Wmissing-format-attribute -Woverloaded-virtual -W  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -rdynamic CMakeFiles/unit_tests.dir/mainTestRunner.cpp.o CMakeFiles/unit_tests.dir/test_basicio.cpp.o CMakeFiles/unit_tests.dir/test_types.cpp.o CMakeFiles/unit_tests.dir/test_tiffheader.cpp.o CMakeFiles/unit_tests.dir/test_futils.cpp.o CMakeFiles/unit_tests.dir/test_enforce.cpp.o CMakeFiles/unit_tests.dir/test_safe_op.cpp.o CMakeFiles/unit_tests.dir/test_XmpKey.cpp.o CMakeFiles/unit_tests.dir/test_DateValue.cpp.o CMakeFiles/unit_tests.dir/test_TimeValue.cpp.o CMakeFiles/unit_tests.dir/test_cr2header_int.cpp.o CMakeFiles/unit_tests.dir/test_helper_functions.cpp.o CMakeFiles/unit_tests.dir/test_slice.cpp.o CMakeFiles/unit_tests.dir/test_image_int.cpp.o CMakeFiles/unit_tests.dir/__/src/basicio.cpp.o CMakeFiles/unit_tests.dir/__/src/bigtiffimage.cpp.o CMakeFiles/unit_tests.dir/__/src/bmpimage.cpp.o CMakeFiles/unit_tests.dir/__/src/convert.cpp.o CMakeFiles/unit_tests.dir/__/src/cr2image.cpp.o CMakeFiles/unit_tests.dir/__/src/crwimage.cpp.o CMakeFiles/unit_tests.dir/__/src/datasets.cpp.o CMakeFiles/unit_tests.dir/__/src/easyaccess.cpp.o CMakeFiles/unit_tests.dir/__/src/epsimage.cpp.o CMakeFiles/unit_tests.dir/__/src/error.cpp.o CMakeFiles/unit_tests.dir/__/src/exif.cpp.o CMakeFiles/unit_tests.dir/__/src/futils.cpp.o CMakeFiles/unit_tests.dir/__/src/gifimage.cpp.o CMakeFiles/unit_tests.dir/__/src/http.cpp.o CMakeFiles/unit_tests.dir/__/src/image.cpp.o CMakeFiles/unit_tests.dir/__/src/ini.cpp.o CMakeFiles/unit_tests.dir/__/src/iptc.cpp.o CMakeFiles/unit_tests.dir/__/src/jp2image.cpp.o CMakeFiles/unit_tests.dir/__/src/jpgimage.cpp.o CMakeFiles/unit_tests.dir/__/src/metadatum.cpp.o CMakeFiles/unit_tests.dir/__/src/mrwimage.cpp.o CMakeFiles/unit_tests.dir/__/src/orfimage.cpp.o CMakeFiles/unit_tests.dir/__/src/pgfimage.cpp.o CMakeFiles/unit_tests.dir/__/src/preview.cpp.o CMakeFiles/unit_tests.dir/__/src/properties.cpp.o CMakeFiles/unit_tests.dir/__/src/psdimage.cpp.o CMakeFiles/unit_tests.dir/__/src/rafimage.cpp.o CMakeFiles/unit_tests.dir/__/src/rw2image.cpp.o CMakeFiles/unit_tests.dir/__/src/tags.cpp.o CMakeFiles/unit_tests.dir/__/src/tgaimage.cpp.o CMakeFiles/unit_tests.dir/__/src/tiffimage.cpp.o CMakeFiles/unit_tests.dir/__/src/types.cpp.o CMakeFiles/unit_tests.dir/__/src/value.cpp.o CMakeFiles/unit_tests.dir/__/src/version.cpp.o CMakeFiles/unit_tests.dir/__/src/webpimage.cpp.o CMakeFiles/unit_tests.dir/__/src/xmp.cpp.o CMakeFiles/unit_tests.dir/__/src/xmpsidecar.cpp.o CMakeFiles/unit_tests.dir/__/src/pngimage.cpp.o CMakeFiles/unit_tests.dir/__/src/asfvideo.cpp.o CMakeFiles/unit_tests.dir/__/src/matroskavideo.cpp.o CMakeFiles/unit_tests.dir/__/src/quicktimevideo.cpp.o CMakeFiles/unit_tests.dir/__/src/riffvideo.cpp.o CMakeFiles/unit_tests.dir/__/src/utilsvideo.cpp.o CMakeFiles/unit_tests.dir/__/src/canonmn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/casiomn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/cr2header_int.cpp.o CMakeFiles/unit_tests.dir/__/src/crwimage_int.cpp.o CMakeFiles/unit_tests.dir/__/src/fujimn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/helper_functions.cpp.o CMakeFiles/unit_tests.dir/__/src/image_int.cpp.o CMakeFiles/unit_tests.dir/__/src/makernote_int.cpp.o CMakeFiles/unit_tests.dir/__/src/minoltamn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/nikonmn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/olympusmn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/orfimage_int.cpp.o CMakeFiles/unit_tests.dir/__/src/panasonicmn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/pentaxmn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/rw2image_int.cpp.o CMakeFiles/unit_tests.dir/__/src/samsungmn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/sigmamn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/sonymn_int.cpp.o CMakeFiles/unit_tests.dir/__/src/tags_int.cpp.o CMakeFiles/unit_tests.dir/__/src/tiffcomposite_int.cpp.o CMakeFiles/unit_tests.dir/__/src/tiffimage_int.cpp.o CMakeFiles/unit_tests.dir/__/src/tiffvisitor_int.cpp.o CMakeFiles/unit_tests.dir/__/src/pngchunk_int.cpp.o  -o ../bin/unit_tests ../lib/libexiv2-xmp.a /usr/lib64/libcurl.so /usr/lib64/libz.so /usr/lib64/libgtest.so /usr/lib64/libgtest_main.so /usr/lib64/libz.so /usr/lib64/libexpat.so /usr/lib64/libgtest.so /usr/lib64/libgtest_main.so -lpthread -lc 
/usr/bin/ld: /tmp/unit_tests.UeJpy3.ltrans16.ltrans.o:(.data.rel.ro+0x10): undefined reference to `typeinfo for testing::Test&apos;
/usr/bin/ld: /tmp/unit_tests.UeJpy3.ltrans16.ltrans.o:(.data.rel.ro+0x28): undefined reference to `typeinfo for testing::Test&apos;
/usr/bin/ld: /tmp/unit_tests.UeJpy3.ltrans19.ltrans.o:(.data.rel.ro+0x10): undefined reference to `typeinfo for testing::Test&apos;
/usr/bin/ld: /tmp/unit_tests.UeJpy3.ltrans19.ltrans.o:(.data.rel.ro+0x28): undefined reference to `typeinfo for testing::Test&apos;
/usr/bin/ld: /tmp/unit_tests.UeJpy3.ltrans19.ltrans.o:(.data.rel.ro+0x40): undefined reference to `typeinfo for testing::Test&apos;
/usr/bin/ld: /tmp/unit_tests.UeJpy3.ltrans19.ltrans.o:(.data.rel.ro+0x58): more undefined references to `typeinfo for testing::Test&apos; follow
collect2: error: ld returned 1 exit status
make[2]: *** [unitTests/CMakeFiles/unit_tests.dir/build.make:1282: bin/unit_tests] Error 1
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/exiv2-0.27.2&apos;
make[1]: *** [CMakeFiles/Makefile2:350: unitTests/CMakeFiles/unit_tests.dir/all] Error 2
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/exiv2-0.27.2&apos;
make: *** [Makefile:133: all] Error 2
</pre>

**Comment by clanmills** [comment] 2019-09-07 11:24
This is a remarkable find as the CI builds everything on many platforms!

Questions:
1) What is your platform?
2) Is this on the source bundle from the web site, or a branch in GitHub?

**Comment by clanmills** [comment] 2019-09-07 15:41
I've pulled down the source bundle of exiv2 v0.27.2 from https://exiv2.org and built it with unit_tests on Ubuntu with GCC 7.4.0
```
rmills@rmillsmbp-ubuntu:/media/psf/Home/Downloads/exiv2-0.27.2-Source/build$ uname -a
Linux rmillsmbp-ubuntu 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
rmills@rmillsmbp-ubuntu:/media/psf/Home/Downloads/exiv2-0.27.2-Source/build$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rmills@rmillsmbp-ubuntu:/media/psf/Home/Downloads/exiv2-0.27.2-Source/build$ bin/unit_tests 
[==========] Running 126 tests from 34 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from MemIo
[ RUN      ] MemIo.seek_out_of_bounds_00
[       OK ] MemIo.seek_out_of_bounds_00 (1 ms)
...
[----------] Global test environment tear-down
[==========] 126 tests from 34 test cases ran. (41 ms total)
[  PASSED  ] 126 tests.
Tests finished with return value: 0
rmills@rmillsmbp-ubuntu:/media/psf/Home/Downloads/exiv2-0.27.2-Source/build $ 
```

**Comment by clanmills** [comment] 2019-09-07 18:42
I think this has something to do with gtest.
```
rmills@rmillsmbp-ubuntu:/usr/local/lib$ nm --demangle libgtest.so | grep testing::Test$ | grep typeinfo
00000000002baa48 V typeinfo for testing::Test
000000000009fb50 V typeinfo name for testing::Test
rmills@rmillsmbp-ubuntu:/usr/local/lib$ 
```

I built gtest as described here:  https://github.com/Exiv2/exiv2/issues/575 (and recommended in README.md 4.3 Unit Tests).

I need more information about your environment (platform, compiler, build options, and code version) to make progress with this.  I'm going to close this for now.  I'll be happy to reopen and investigate when there's more information.

**Comment by kloczek** [comment] 2019-09-08 10:55
So looks like gtest is not LTO ready because in my case those symbols have been removed during LTO optimiosation :/

**Comment by clanmills** [comment] 2019-09-08 11:43
I've never heard of LTO (Link Time Optimization), however our friends at Google have:  https://gcc.gnu.org/wiki/LinkTimeOptimization

I have successfully built the unit tests as follows:
```
.../exiv2-0.27.2-Source/build$ rm -rf CM*
.../exiv2-0.27.2-Source/build$ cmake .. -DEXIV2_BUILD_UNIT_TESTS=On -DCMAKE_CXX_FLAGS=-flto
.../exiv2-0.27.2-Source/build$ grep CMAKE_CXX_FLAGS CMakeCache.txt 
//Choose the type of build, options are: None(CMAKE_CXX_FLAGS or
CMAKE_CXX_FLAGS:STRING=-flto
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
//ADVANCED property for variable: CMAKE_CXX_FLAGS
CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_DEBUG
CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_MINSIZEREL
CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_RELEASE
CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_RELWITHDEBINFO
CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
rmills@rmillsmbp-ubuntu:/media/psf/Home/Downloads/exiv2-0.27.2-Source/build$ 
```

I think you are reporting missing symbols in your installed version of libgtest.so and I recommend that you follow the recommended procedure in #575 to build/install google test.

**Comment by D4N** [comment] 2019-09-08 22:13
@kloczek judging from the output that you provided: are you building an RPM on Fedora/RHEL with LTO enabled? If yes, could you post the spec file and some details about your platform (if you are using mock, which mock root, etc.)?

I'll try to reproduce your issue then, but it looks like an issue with gtest to be honest.

**Comment by clanmills** [comment] 2019-09-08 22:32
Dan:  You never cease to amaze me.  Thanks for getting involved after my rejection of this issue.

**Comment by clanmills** [comment] 2019-09-15 07:47
Pushing this to Exiv2 v0.27.4 (scheduled for 2019-12-31).

**Comment by clanmills** [comment] 2021-04-13 12:40
This issue hasn't been updated for a couple of years.  I'm going to close it.  If new information comes to light, I will be happy to reopen this issue.

**Closed by clanmills** 2021-04-13 12:40 UTC
Labels: notReproducible
