### ISSUE TITLE
JXR Format support

### ISSUE THREAD

**Issue by SplitGemini** [Exiv2/exiv2#2878] opened 2024-01-02 13:57 UTC
#### **Is your feature request related to a problem?**
No.

#### **Describe the solution you would like**
I want get EXIF from a [JXR](https://en.wikipedia.org/wiki/JPEG_XR) file.

#### **Describe alternatives you have considered**
Dump from exiv2: 
```text
.\exiv2.exe "Alan Wake 2 2024_1_1 17_07_43.jxr"
File name       : Alan Wake 2 2024_1_1 17_07_43.jxr
File size       : 14278162 Bytes
MIME type       : image/tiff
Image size      : 0 x 0
Thumbnail       : None
Camera make     :
Camera model    :
Image timestamp :
File number     :
Exposure time   :
Aperture        :
Exposure bias   :
Flash           :
Flash bias      :
Focal length    :
Subject distance:
ISO speed       :
Exposure mode   :
Metering mode   :
Macro mode      :
Image quality   :
White balance   :
Copyright       :
Exif comment    :
```

Dump from exiftool:
```text
ExifTool Version Number         : 12.72
File Name                       : Alan Wake 2 2024_1_1 17_07_43.jxr
Directory                       : 
File Size                       : 14 MB
File Modification Date/Time     : 2024:01:01 17:07:44+08:00
File Access Date/Time           : 2024:01:02 21:53:29+08:00
File Creation Date/Time         : 2024:01:01 17:07:43+08:00
File Permissions                : -rw-rw-rw-
File Type                       : JXR
File Type Extension             : jxr
MIME Type                       : image/jxr
Exif Byte Order                 : Little-endian (Intel, II)
About                           : uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b
Id                              : b4517361-573b-4479-ae81-cad4a6406eeb
Title                           : Alan Wake 2
Author                          : Microsoft Game DVR
Basic                           : 0!!!!f411a640-05da-47b1-9b30-7f69d5ee6948!!0!!1!!1337!!2007965160
Basic Hash                      : cf367a358dd9f4ae5df9684a98b196cefbb7c9d39ff0b64665495b9f9a47be62
Extended                        : 
Pixel Format                    : 64-bit RGBA Half
Transformation                  : Horizontal (normal)
Image Type                      : (none)
Image Width                     : 2560
Image Height                    : 1440
Width Resolution                : 96
Height Resolution               : 96
Image Offset                    : 1178
Image Byte Count                : 14268658
Alpha Offset                    : 14269836
Alpha Byte Count                : 8326
Image Size                      : 2560x1440
Megapixels                      : 3.7
```

#### **Desktop**
- OS and version: Window 11
- Exiv2 version and source: 0.28.1
- Any software using exiv2 and source: just exiv2 command line tool

**Comment by kmilos** [comment] 2024-01-02 16:17
Duplicate of https://github.com/Exiv2/exiv2/issues/2120

Please search before opening new issues.

**Closed by kmilos** 2024-01-02 16:17 UTC
Labels: request
