### ISSUE TITLE
regression of '-g' between 0.25 and 0.26

### ISSUE THREAD

**Issue by joerncgm** [Exiv2/exiv2#818] opened 2019-05-03 07:25 UTC
In version 0.25, -g produced this desired output:

```
$ exiv2 -g '.*'  foo.jpg
Exif.Image.Make                              Ascii      18  NIKON CORPORATION
Exif.Image.Model                             Ascii      11  NIKON D750
Exif.Image.Orientation                       Short       1  top, left
Exif.Image.XResolution                       Rational    1  300
Exif.Image.YResolution                       Rational    1  300
Exif.Image.ResolutionUnit                    Short       1  inch
```

in version 0.26 this no longer works:

```
$ exiv2 -g '.*' foo.jpg
File name       : foo.jpg
File size       : 194825 Bytes
MIME type       : image/jpeg
Image size      : 800 x 600
Camera make     : NIKON CORPORATION
Camera model    : NIKON D750
Image timestamp : 2019:04:27 14:56:34
```

I didn't find any bug report for this and can't test if it is fixed in 0.27.x, because compilation fails for me (NetBSD 8.0/amd64, GCC 5.5.0) with

```
[ 26%] Building CXX object src/CMakeFiles/exiv2lib.dir/convert.cpp.o
/home/joern/exiv/head/exiv2/src/convert.cpp: In function 'bool {anonymous}::convertStringCharsetIconv(std::string&, const char*, const char*)':
/home/joern/exiv/head/exiv2/src/convert.cpp:1530:44: error: invalid conversion from 'char**' to 'const char**' [-fpermissive]
                               &outbytesleft);
                                            ^
In file included from /home/joern/exiv/head/exiv2/src/convert.cpp:56:0:
/usr/include/iconv.h:46:8: note:   initializing argument 2 of 'size_t iconv(iconv_t, const char**, size_t*, char**, size_t*)'
 size_t iconv(iconv_t, const char ** __restrict,
        ^
gmake[2]: *** [src/CMakeFiles/exiv2lib.dir/build.make:102: src/CMakeFiles/exiv2lib.dir/convert.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:362: src/CMakeFiles/exiv2lib.dir/all] Error 2
gmake: *** [Makefile:130: all] Error 2
```

NetBSD bundles it own libiconv. I could easily install GNU libiconv 1.14, but I have no idea how to tell CMake to use it.

**Comment by clanmills** [comment] 2019-05-03 09:17
Ah yes, I know the story about --grep.  Don't know about NetBSD/libiconv
 
### Grep

The grep code was reworked for 0.26 about 3 years ago.  It used to be a "sub-string" match and was enhanced to use regular expressions when available to the compiler.  You should be able to find out the compiler setting: `$ exiv2 --version --verbose --grep grep`.  There are several possibilities:

0 Sub-string
1 Compiler found <regex.h>
2 Compiler found <regex> (C++ 11)

Regrettfully, this has been disturbed and isn't being reported in v0.27  You can inspect the value in exv_conf.h:
```
1113 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ grep REGEX exv_conf.h 
#define EXV_HAVE_REGEX_H
1114 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

Somebody did report a bug concerning --grep no longer applying to the default command `$ exiv2 foo`.  In re-engineering the grep code, I hadn't realised that --grep was used by the default command.  I did investigate and decided to do nothing about this at the time.  I can't find the bug report about that.  It was report on Redmine:  https://dev.exiv2.org/projects/exiv2/search?all_words=1&attachments=0&changesets=1&commit=Search&issues=1&messages=1&news=1&options=0&page=6&q=grep&scope=&titles_only=&utf8=✓&wiki_pages=1

I'll assign this to milestone 0.27.2 and fix it.  Exiv2 0.27.2 is scheduled for release on 2019-06-30

### NetBSD/libiconv

CMake searches for the include file iconv.h with the code on cmake/FindIconv.cmake.  I can't remember anything about that code.  Perhaps you could read it and find out what ought to happen.  CMake searches and set flags in exv_conf.h
```
1119 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ grep -i icon exv_conf.h 
/* Define to `const' or to empty, depending on the second argument of `iconv'. */
/* #undef ICONV_ACCEPTS_CONST_INPUT */
#if defined ICONV_ACCEPTS_CONST_INPUT
#define EXV_ICONV_CONST const
#define EXV_ICONV_CONST
// Define if you have the iconv function.
#define EXV_HAVE_ICONV
1120 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```
So, when iconv isn't available, the compiler should omit that when it compiles convert.cpp.  I can't remember what iconv does for exiv2 (character set conversions or something) and this feature is marginal for most users.

There's a note in README.md concerning Cygwin:
```
Download and build libiconv-1.15: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz
```
Could you try building and installing libiconv-1.15 and perhaps all will be well.

**Comment by joerncgm** [comment] 2019-05-03 10:15
Thanks for the quick and thorough reply!

Before addressing your suggestions: Is there any other option to make 
0.26 emit all the "raw" EXIF keys (i.e. something like 
"Exif.Image.Model")? I could easily do the grepping later.


Am 03.05.2019 um 11:17 schrieb Robin Mills:
> available to the compiler. You should be able to find out the compiler 
> setting: |$ exiv2 --version --verbose --grep grep|. There are several 
> possibilities:
> 
> 0 Sub-string
> 1 Compiler found <regex.h>
> 2 Compiler found (C++ 11)

$ exiv2 --version --verbose --grep regex

yields "have_regex=1" for both 0.25 and 0.26, so this does not seem to 
be the main problem. The build for 0.27 creates an exv_conf.h with

#define EXV_HAVE_REGEX_H

while the older versions have

#define EXV_HAVE_REGEX 1

so I assume that 0.27, would it compile, have no regex support.

> There's a note in README.md concerning Cygwin:
> 
> |Download and build libiconv-1.15: 
> https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz |
> 
> Could you try building and installing libiconv-1.15 and perhaps all will 
> be well.

I have never managed to understand CMake. All that I need here (and 
every time I had similar problems with CMake-based projects) is the 
equivalent to

CPPFLAGS=-I... LDFLAGS=-L... ./configure

i.e. how do I tell CMake "this is the directory tree with all my headers 
and libraries, just look there". Unfortunately, the Cygwin explanation 
assumes, that libiconv is installed in the same tree as all other 
dependencies.

Joern

-- 
Jörn Clausen
Daten- und Rechenzentrum
GEOMAR Helmholtz-Zentrum für Ozeanforschung Kiel
Düsternbrookerweg 20
24105 Kiel

**Comment by clanmills** [comment] 2019-05-03 11:11
Good News.  Yes, you have lots of control over the output.  The --grep option applies with every version of the -pmod.  When you don't use -pmod, grep's broken (that's the bug you and somebody else have reported).  There are lots of modifiers such as -pe (Exif), -pX (Xmp), -pa (All).  So:

```
1120 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 -pe http://clanmills.com/Stonehenge.jpg
Exif.Image.Make                              Ascii      18  NIKON CORPORATION
Exif.Image.Model                             Ascii      12  NIKON D5300
...
1121 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 -pa -g Model http://clanmills.com/Stonehenge.jpg
Exif.Image.Model                             Ascii      12  NIKON D5300
Iptc.Envelope.ModelVersion                   Short       1  4
1122 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

The team had a discussion about Grep when I was on vacation and I didn't pay close attention.  That's when have_grep was lost overboard and I'll put that back in v0.27.2  They rejected the C++11 `include <regex>` sniffer and deferred that for v0.28 (scheduled for 2020).  So it sniffs for `#include <regex.h>` and nothing else.

I recommend that you become familiar with CMake as it has mostly replaced autotools.  It's worth the effort.  And conan is very good for locating and building dependencies.  Have a read at README-CONAN.md and life might be easier.

CMake generates a `Makefile`, so you can set and pass environment setting to `$ make CFLAGS=bhabha LDFLAGS=blacksheep` and so on.  If you want to bake those flags into your makefile (as you would with `./configure`) you can set CMAKE_C_FLAGS on the cmake command line:
```
$ mkdir build ; cd build ; cmake .. '-DCMAKE_C_FLAGS-I think I saw a pussy cat'
```

CMake has lots of variables you can set from the command line which are about equivalent to CC, LDFLAGS, CFLAGS, CXXFLAGS etc in autotools.  Why didn't the CMake people not adopt the same autotools keys?  Ask them! 

I have a good feeling about our conversation.  We're going to get everything fixed for you over the weekend.  Life will be good, you'll see.

**Comment by clanmills** [comment] 2019-05-04 15:06
I've installed a NetBSD VM on my MacMini desktop.

I've got exiv2 to build and (mostly) pass the test suite.  I think the issue in src/convert.cpp is that the signature of the iconv() function on NetBSD is different from "the standard".  I modified the code in src/convert.cpp to `#undef EXV_HAVE_ICONV` and everything builds with "pure CMake" (with conan).

```
$ mkdir build ; cd build ; cmake .. ; make ; make tests
```

I installed python37, python27, pip, conan, bash and expat.  I downloaded and built md5sum.c and added links for /usr/pkg/bin/python3 and /bin/bash.  All rather tedious.  However with a little effort, it works.

The test suite is reporting exceptions concerning character conversion because, although exiv2 believes that iconv() is in the build, it was hacked out.  The test suite is correctly detecting/reporting this.  There are also oddities involving md5sum.

I installed conan.  It reports:
```
ERROR: Invalid setting 'NetBSD' is not a valid 'settings.os' value.
```
I could talk to the Conan folks about this, however I won't because it's easy to build with "pure CMake".

I'm 100% optimistic that Exiv2 will build "out of the box" on NetBSD.  I'll spend more time on this on Sunday evening.  It's likely that the fix is to get FindIconv.cmake to return False on NetBSD.  I will investigate building/installing iconv() 1.15 using the bundle I mentioned above.  

We use GitLab to test our builds on many platforms and linux distros.  When I have made the necessary changes to say "I believe everything works on NetBSD", I'll discuss with other team members about getting GitLab to build on NetBSD.

**Comment by clanmills** [comment] 2019-05-05 07:34
Progress update.

### Iconv
I've investigated building iconv 1.15 and that doesn't help.  CMake is correctly reporting `Iconv_IS_BUILT_IN`.  

The signature of iconv() on NetBSD expect a "const char*.  There's a symbol EXV_ICONV_CONST in exv_conf.h to provide that.  It's not being correctly set on NetBSD.  When I set it, the code builds.

I haven't discovered yet how that gets see (or not set)

### md5sum

We need a link for /usr/bin/md5sum -> /usr/bin/md5

The output of md5 on NetBSD is totally different from other platforms (such as MacOSX)
```
518 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ uname -a
Darwin rmillsmm-local.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
519 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ md5sum ../src/convert.cpp 
48987145f25141225d3ab4af99a0c131  ../src/convert.cpp
520 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ 

localhost$ uname -a
NetBSD localhost 8.0 NetBSD 8.0 (GENERIC) #0: Tue Jul 17 14:59:51 UTC 2018  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
localhost$ md5sum ../src/convert.cpp 
908228047 70287 ../src/convert.cpp
localhost$ 
```

### Grep

No progress on this at the moment.  I'm going to open a new issue for NetBSD and retain this for the original report concerning `exiv2 -g`

**Comment by clanmills** [comment] 2019-05-06 18:17
Progress update on the `$ exiv2 -g foo image...` command.  The fix is:
```
1196 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ git diff
diff --git a/src/actions.cpp b/src/actions.cpp
index 34a7a80d..68260186 100644
--- a/src/actions.cpp
+++ b/src/actions.cpp
@@ -243,7 +243,7 @@ namespace Action {
             int rc = 0;
             Exiv2::PrintStructureOption option = Exiv2::kpsNone ;
             switch (Params::instance().printMode_) {
-                case Params::pmSummary:   rc = printSummary();     break;
+                case Params::pmSummary:   rc = Params::instance().greps_.empty() ? printSummary() : printList(); break;
                 case Params::pmList:      rc = printList();        break;
                 case Params::pmComment:   rc = printComment();     break;
                 case Params::pmPreview:   rc = printPreviewList(); break;
1197 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I'll submit a PR in the next few days to the branch 0.27-maintenance.  I'll also add a regression detector to the test suite to ensure this feature is no "lost overboard" again.  I'll also update the man page src/exiv2.1 to document this feature of the exiv2 command-line program.

**Comment by joerncgm** [comment] 2019-05-07 11:34
Hi Robin!

> I'll submit a PR in the next few days to the branch 0.27-maintenance. 
> I'll also add a regression detector to the test suite to ensure this 
> feature is no "lost overboard" again. I'll also update the man page 
> src/exiv2.1 to document this feature of the exiv2 command-line program.

Thanks for all the effort you are putting into this, it's more than I 
could ever have asked for!

As I install my software using pkgsrc, I'll inform the pkgsrc 
maintainers to update the corresponding package as soon as the fix is 
released.

-- 
Jörn Clausen
Daten- und Rechenzentrum
GEOMAR Helmholtz-Zentrum für Ozeanforschung Kiel
Düsternbrookerweg 20
24105 Kiel

**Comment by clanmills** [comment] 2019-05-09 11:07
Thank you for your kind words.  I've submitted the PRs for your issues #818 (#831) and #823 (#833).

Exiv2 v0.27.2 is scheduled for 2019-06-30 and is on-track at present.  The release announcement on Facebook and if you "Like" our page, you'll get a notification.  https://www.facebook.com/exiv2/

I'm rather pleased with this issue.  An issue was raised concerning FreeBSD with v0.27.0 RC1.  It's good to visit both NetBSD and FreeBSD and give stronger support to Unix.

**Closed** 2019-05-11 18:03 UTC
Labels: bug, to-master
