### ISSUE TITLE
Docs: Exif.Image.DateTimeOriginal should be Exif.Photo.DateTimeOriginal

### ISSUE THREAD

**Issue by butcherg** [Exiv2/exiv2#1467] opened 2021-02-05 16:58 UTC
**Describe the bug**
https://www.exiv2.org/tags.html describes Exif.Image.DateTimeOriginal.  Should be Exif.Photo.DateTimeOriginal.

**Comment by clanmills** [comment] 2021-02-05 18:23
Yes.  That's quite correct, Glenn.  Thank You for bringing this to my attention. Nice to speak to you from my domain.

```
525 rmills@rmillsm1:~/gnu/exiv2/team/book $ exiv2 --grep original/i ~/Stonehenge.jpg 
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
Exif.Photo.SubSecTimeOriginal                Ascii       3  00
526 rmills@rmillsm1:~/gnu/exiv2/team/book $
```

This is very surprising because those pages are generated automatically from the tag definitions in the code base.  Nice puzzle to finish the week.  

I suspect this issue has been present for 10+ years without being spotted.  So, I wonder what else lies at the bottom of the swamp. I'll fix this in the code base and the web pages will be updated with Exiv2 v0.27.4 on 2021-05-22.

**Comment by butcherg** [comment] 2021-02-05 18:44
Thanks.  After watching @carvac struggle with my hack libtiff code snippet in Filmulator, I decided to bite the bullet and move to exiv2 in rawproc.  I settled on a metadata subset appropriate to output renditions, and coded routines to  load and save that subset using exiv2.  All good, except libtiff would complain about "unidentified tag 0x9003" when opening tiffs saved with exiv2 DateTimeOriginal tags.  Weird, I thought, the tag is in the lilbtiff EXIF list, went through a whole bunch of work to suppress the error when I noticed with exiftool -v where the tag was being placed. 2+2....

I'm now going to work internal regressions, tools in rawproc that are expecting tags and values differently than what my hack code provided.  After that, I'm considering configurable tag sets; in doing that I may discover other such Exif.Photo.DateTimeOriginal things.  If I find stuff, I'll report it here.

**Comment by kmilos** [comment] 2021-02-05 18:54
Sorry to spoil the party gents, but DateTimeOriginal is part of TIFF/EP as well, and should stay in IFD0, i.e. Exif.Image.DateTimeOriginal, I don't think this was an accident.

**Comment by clanmills** [comment] 2021-02-05 18:55
Fixing this seems easy.  The tag has been included in both ifdTagInfo vector and exifTagInfo in src/tags_int.cpp  That's not correct, it should only be in exifTagInfo.  I'm going to have to review every tag in ifdTagInfo.

I thought you had spotted this with your eagle eyes.  Sounds as though this has disturbed your code.  What's your urgency for a patch with this?

This team-work stuff really works.  I wonder why nobody uses it in the office.

**Comment by kmilos** [comment] 2021-02-05 18:56
> Fixing this seems easy. The tag has been included in both ifdTagInfo vector and exifTagInfo in src/tags_int.cpp That's not correct, it should only be in exifTagInfo. I'm going to have to review every tag in ifdTagInfo.

It is really duplicated between TIFF/EP (IFD0) and Exif (Exif IFD). I made a pass already couple of weeks a go, but another one doesn't hurt.

**Comment by butcherg** [comment] 2021-02-05 19:00
DateTime is in the TIFF tag list; DateTimeOriginal  is not:  http://www.libtiff.org/man/TIFFGetField.3t.html

**Comment by kmilos** [comment] 2021-02-05 19:03
> DateTime is in the TIFF tag list; DateTimeOriginal is not: http://www.libtiff.org/man/TIFFGetField.3t.html

So? This say nothing about which IFD it belongs to.

Please read the [Exif](http://www.cipa.jp/std/documents/download_e.html?DC-008-Translation-2019-E) and [TIFF/EP](http://www.barrypearson.co.uk/top2009/downloads/TAG2000-22_DIS12234-2.pdf) specs carefully, and then also [this](https://en.wikipedia.org/wiki/TIFF/EP#Differences_from_TIFF_and_Exif).

**Comment by clanmills** [comment] 2021-02-05 19:03
@kmilos Thanks for speaking about about this.  Maybe we only have to ensure that Exif.Photo.DateTimeOriginal comes first in the output of `taglist` to be sure that it gets documented appropriately.

```
        TagInfo(0x9003, "DateTimeOriginal", N_("Date Time Original"), N_("The date and time when the original image data was generated."), ifd0Id, tiffEp, asciiString, 20, printValue), // TIFF/EP tag
.....
        TagInfo(0x9003, "DateTimeOriginal", N_("Date and Time (original)"),
                N_("The date and time when the original image data was generated. "
                "For a digital still camera the date and time the picture was taken are recorded."),
                exifId, dateTime, asciiString, 20, printValue),
```

However as _**you've correctly said**_ it should be in both, so this might still ripple into Glenn's code.

Life is usually not as easy as we hope!  But, you know, it's 19:00 on Friday evening and we have steak and red-wine to deal with.  Tomorrow is another day.

**Comment by kmilos** [comment] 2021-02-05 19:08
> Maybe we only have to ensure that Exif.Photo.DateTimeOriginal comes first in the output of `taglist` to be sure that it gets documented appropriately.

Apart from historical, why would there be a reason to assign any preference to the order, why would Exif take precedence over TIFF/EP?

Bon apetit!

**Comment by clanmills** [comment] 2021-02-05 19:11
Good point.  It should be documented twice.

Let's get some feedback from Glenn about the impact of this on his code.

**Comment by butcherg** [comment] 2021-02-05 19:13
> I thought you had spotted this with your eagle eyes. Sounds as though this has disturbed your code. What's your urgency for a patch with this?

Ha, my 'eagle eyes' kept seeing a warning libtiff dialog box when I'd open TIFFs, irritated me to no end...  :D

No real disturbance; I just decided to get out from under my hack handling of metadata, dealing directly with the image libs.  

@kmilos, libtiff complains if DateTimeOriginal is in IFD0, doesn't if it's in the EXIFFD.  Not sure where to complain about that...

**Comment by kmilos** [comment] 2021-02-05 19:18
@butcherg Complains as if throws an error and crashes your program? If so the address is https://gitlab.com/libtiff/libtiff/-/issues

Nothing stops you from writing to Exif.Photo.DateTimeOriginal when you're creating a non-TIFF/EP file as we have both tags/locations defined in exiv2.

**Comment by butcherg** [comment] 2021-02-05 19:41
> Let's get some feedback from Glenn about the impact of this on his code.

Well, exiv2 will happily read and write Exif.Photo.DateTimeOriginal, and libtiff doesn't complain, so it would seem to me to be something that can be handled in documentation.  I just spent a day chasing an assert with no real indication regarding what was wrong.  Now, it's abundantly clear that libtiff doesn't comply with ISO/DIS 12234-2, but that doesn't keep the warning from showing up.  Further reading of 12234-2, this spec is for TIFF/EP, TIFF 6.0, which may not be what libtiff currently ascribes to.  The libtiff site has links to their conformant specs, but none of them work.

Me, I now know how to make exiv2 cooperate with libtiff with DateTimeOriginal, but it is probably at least worth making some note of the discordance in the exiv2 docs as this situation is hard to chase in the TIFF compendium...

**Comment by kmilos** [comment] 2021-02-05 19:49
I'm sorry if I come across being difficult, that's not the intention. But just playing the devil's advocate here:

AFAICT, exiv2 does the right thing when it comes to TIFF 6.0, TIFF/EP, and Exif.

So why should exiv2 document discrepancies in libtiff?

**Comment by butcherg** [comment] 2021-02-05 20:03
> So why should exiv2 document discrepancies in libtiff?

I don't particularly consider this to be a libtiff discrepancy.  They apparently comply to 4.0, and this library is the predominant means to deal with TIFFs in the mainstream computing world, so one might argue the "standard" is still 4.0

I have no idea regarding the angst and ambitions of the TIFF community; I'm just an application programmer who needs to read and write TIFFs.  It would seem prudent for exiv2 to document the state of affairs for such vermin as I...  :D

**Comment by kmilos** [comment] 2021-02-05 20:23
I don't think more than "Beware of overlap and differences between Exif and TIFF/EP" is necessary.

**Comment by clanmills** [comment] 2021-02-06 08:30
Gentlemen:  Wonderful dinner and woke up feeling a little less than 9/10. 

Could 1467 be a documentation error?.  No!  Both Exif.Image.DateTimeOriginal and Exif.Photo.DateTimeOriginal are displayed on: https://exiv2.org/tags.html

Two conclusions:

1. There is no case to answer.  That tag is valid in both IFDs
2. I enjoyed our conversation about this.

As you both know, I'm trying to retire.  When I see such a vigorous and knowledgeable discussion, I know the Community can look after Exiv2 in the future.  Thank You both for participating.

TIFF6.pdf (the 1992 Adobe Spec) doesn't mention DateTimeOriginal.  Exif added in the the exifIFD.  Milo&scaron; is correct that it's in the TIFF/EP Standard as "Mandatory".  TAG2000-22_DIS12234-2.pdf  If lib tiff implements TIFF6.pdf exactly, it will not know this tag.  Should libtiff comply with TIFF/EP?  That's a discussion for libtiff. 

@butcherg.  I think we've beaten this to death and I invite you to close this issue.

![screenshot_44](https://user-images.githubusercontent.com/529982/107112845-9e74e500-6852-11eb-9452-b0bf2e0df2fe.png)
![screenshot_43](https://user-images.githubusercontent.com/529982/107112846-a2086c00-6852-11eb-8f61-1773a5e1efcf.png)

**Comment by kmilos** [comment] 2021-02-06 09:13
@butcherg I don't think there is any particular angst. TIFF has over decades become a behemoth of a format and the tentacles spread far and wide. As you found out, one just has to roll up the sleeves ;)

LibTIFF already partially supports TIFF/EP through addition of tags like [TIFFTAG_CFAPATTERN](https://gitlab.com/libtiff/libtiff/-/merge_requests/120). But this is to support reading/writing files like NEF, DNG, etc. It is, and IMHO should remain focused on implementing all the possible TIFF _file format_ features so we can access and create a variety of TIFF-based files, not policing higher level metadata schemes.

**Closed** 2021-02-06 16:03 UTC
Labels: documentation

**Comment by butcherg** [comment] 2021-02-06 16:06
Ack, pressed the button, thought of one more thing to consider.  With two separate entries for DateTimeOriginal in the docs, it might be worth considering putting in references to each other.  I didn't know there was a second one for two days...

Now, back to figuring out how to make it all work...

**Comment by kmilos** [comment] 2021-02-06 17:37
> Now, back to figuring out how to make it all work...

If it helps, e.g. darktable does roughly this:

1. Tries to collect the metadata from any possible location for the plethora of input raw formats it can handle
  (this is aided by e.g. [exiv2 "easy accessors" like this one](https://github.com/Exiv2/exiv2/blob/7d2edb532861466c75d7c42ac9f476237a5ead77/src/easyaccess.cpp#L210); otherwise you have to know about and handle the various possibilities yourself)
2. Keeps the metadata in its own data structure during processing
3. On export, it transfers this internal data to exiv2 and stores (most) in Exif.Photo (i.e. Exif IFD)

**Comment by clanmills** [comment] 2021-02-06 18:29
The EasyAccess API is documented here:  https://github.com/Exiv2/exiv2/wiki/EasyAccess-API

Here are the myriad of tags implicated.  I suspect the comments in the description were cut'n'pasted directly from the standards:

```bash
511 rmills@rmillsm1:~/gnu/exiv2/team/book/build $ taglist ALL | csv - | grep DateTimeOriginal
[Image.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[Thumbnail.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[Image2.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[Image3.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[Photo.DateTimeOriginal]	[36867]	[0x9003]	[Photo]	[Exif.Photo.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated. For a digital still camera the date and time the picture was taken are recorded.]	
[Photo.OffsetTimeOriginal]	[36881]	[0x9011]	[Photo]	[Exif.Photo.OffsetTimeOriginal]	[Ascii]	[Time difference from Universal Time Coordinated including daylight saving time of DateTimeOriginal tag.]	
[Photo.SubSecTimeOriginal]	[37521]	[0x9291]	[Photo]	[Exif.Photo.SubSecTimeOriginal]	[Ascii]	[A tag used to record fractions of seconds for the <DateTimeOriginal> tag.]	
[SubImage1.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage2.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage3.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage4.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage5.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage6.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage7.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage8.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubImage9.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SubThumb1.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[NikonPreview.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
[SamsungPreview.DateTimeOriginal]	[36867]	[0x9003]	[Image]	[Exif.Image.DateTimeOriginal]	[Ascii]	[The date and time when the original image data was generated.]	
512 rmills@rmillsm1:~/gnu/exiv2/team/book/build $ 
```

@butcherg Glenn: I'm happy if you'd like to write an article for our Wiki.  Perhaps we could have a section on the Wiki for _**Application Notes**_.  Another possibility is another sample program "metalint", or "exiflint" which could  report a warning that would have kept you out of trouble.

**Comment by butcherg** [comment] 2021-02-06 19:04
> I'm happy if you'd like to write an article for our Wiki. Perhaps we could have a section on the Wiki for _**Application Notes**_

I think an "Application Notes" page would be quite helpful, and I'd be willing to provide a short writeup on what I experienced.

With regard to finding the tag in an input image, right now my plan is to ingest all metadata from raw files from libraw.  They deliver a data structure with a single DateTime (their definition is more like DateTimeOriginal), and they figure out for the myriad cameras from where to get it.  For output, until libtiff releases a version that figures out TIFF/EP, I'm just going to use the Exif.Photo.DateTimeOriginal tag, as it fits all my output destinations, jpeg, tiff4, and png.

Thanks for all the discussion, it's been quite helpful in my exiv2 integration.

**Comment by kmilos** [comment] 2021-02-06 19:43
I thought you confusion wirh libtiff wrnings came from the read side? If libraw finds all the metadata you need in the right locations, then there is no problem, right?



> For output, until libtiff releases a version that figures out TIFF/EP, I'm just going to use the Exif.Photo.DateTimeOriginal tag, as it fits all my output destinations, jpeg, tiff4, and png.

If all you do is export a processed image, the of course, by all means you _should_ use Exif.Photo for all the relevant Exif tags (and Exif.Image for the basic/common ones Exif spec says go into the main IFD rather than the Exif IFD)!

TIFF/EP is really meant for raw file format interoperability (e.g. NEF, DNG...), so it doesn't sound like it should concern you.

And just a gentle reminder:

>They apparently comply to 4.0, and this library is the predominant means to deal with TIFFs in the mainstream computing world, so one might argue the "standard" is still 4.0

> tiff4

No such thing. LibTIFF is an independent implementation and just happens to be at its version 4.2, and there is prominent [link on their site](http://www.simplesystems.org/libtiff/support.html) that mentions how much of the only relevant TIFF **6.0** baseline spec they cover.

**Comment by butcherg** [comment] 2021-02-06 20:08
> I thought you confusion with libtiff warnings came from the import side? If libraw finds all the metadata you need in the right locations when importing, then there is no problem, right?

No, exiv2 was writing metadata to a TIFF that when later read by libtiff was not palatable.  That was due to my selection of Exif.Image.DateTimeOriginal for that output, based on finding it first in a search of the exiv2 tags.html page.  In hindsight, I should have followed the remaining matches; finding the second hit, Exif.Photo.DateTimeOriginal, might have given me a cluebird...

> If all you do is export a processed (RGB) image, then of course, you _should_ by all mens use Exif.Photo for all the relevant Exif tags (and Exif.Image for the basic/common ones Exif spec says go into the main IFD rather than the Exif IFD)!

In this business I'm a photographer first, who happens to be a programmer.  I have really no particular aspiration to become an image format engineer, although figuring out things like this push me more to become one by default...

**Comment by clanmills** [comment] 2021-02-06 20:40
If you want to know about Image Formats and Metadata, I've (almost finished) writting the book.  _**Caution**_:  It's incredibly detailed and comes with a guaranteed cure for insomnia.  https://clanmills.com/exiv2/book/

If you write something about this, I'll be happy to open a page on the Wiki Titled: "Application Notes" and encourage others to contribute.  For example, I've had private email from somebody this week who wants me to add an option: "Delete all metadata except Exif.Image.Orientation".  Clearly a suitable topic for a script.

I'm a little surprised by your comment that _exiv2 was writing metadata to a TIFF that when later read by libtiff was not palatable_. 

I'm concerned and have reproduced the libtiff/Exif.Image.DateTimeOriginal issue with tiffinfo.  Maybe that's a good "lint for libtiff".  It's a quick way to discover to identify libtiff unhappiness.

I have a copy of Stonehenge.jpg -> Preview -> Stonehenge.tiff in the test files for my book.  

```bash
540 rmills@rmillsm1:~/temp $ cp ~/gnu/exiv2/team/book/files/Stonehenge.tiff .
541 rmills@rmillsm1:~/temp $ exiv2 -g DateTimeOriginal Stonehenge.tiff 
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
542 rmills@rmillsm1:~/temp $ exiv2 -M'set Exif.Image.DateTimeOriginal 2020:02:06 20:18:33' Stonehenge.tiff
543 rmills@rmillsm1:~/temp $ exiv2 -g DateTimeOriginal Stonehenge.tiff 
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
Exif.Image.DateTimeOriginal                  Ascii      20  2020:02:06 20:18:33
```

Sniffing with tiffinfo shows:
```
544 rmills@rmillsm1:~/temp $ tiffinfo --version
tiffinfo: illegal option -- -
LIBTIFF, Version 4.1.0
Copyright (c) 1988-1996 Sam Leffler
Copyright (c) 1991-1996 Silicon Graphics, Inc.

usage: tiffinfo [options] input...
where options are:
 -D		read data
 -i		ignore read errors
 -c		display data for grey/color response curve or colormap
 -d		display raw/decoded image data
 -f lsb2msb	force lsb-to-msb FillOrder for input
 -f msb2lsb	force msb-to-lsb FillOrder for input
 -j		show JPEG tables
 -o offset	set initial directory offset
 -r		read/display raw image data instead of decoded data
 -s		display strip offsets and byte counts
 -w		display raw data in words rather than bytes
 -z		enable strip chopping
 -#		set initial directory (first directory is # 0)
545 rmills@rmillsm1:~/temp $ tiffinfo  Stonehenge.tiff 
TIFFReadDirectory: Warning, Unknown field with tag 36867 (0x9003) encountered.
TIFF Directory at offset 0x8 (8)
  Image Width: 300 Image Length: 200
...
  Make: NIKON CORPORATION
  Model: NIKON D5300
  Software: Ver.1.00 
  DateTime: 2015:07:16 20:25:28
  XMLPacket (XMP Metadata):
...
  RichTIFFIPTC Data: <present>, 92 bytes
  EXIFIFDOffset: 0x1b52
  ICC Profile: <present>, 3144 bytes
  GPSIFDOffset: 0x1dc2
  Tag 36867: 2020:02:06 20:18:33
TIFFReadCustomDirectory: Warning, Unknown field with tag 34864 (0x8830) encountered.
TIFFReadCustomDirectory: Warning, Wrong data type 3 for "GainControl"; tag ignored.
TIFF Directory at offset 0x1b52 (6994)
  ExposureTime: 0.002500
... 
  ExifVersion: 0x30,0x32,0x33,0x30
  DateTimeOriginal: 2015:07:16 15:38:54
  DateTimeDigitized: 2015:07:16 15:38:54
...
  UserComment: 0x41,0x53,0x43,0x49,0x49,0x0,0x0,0x0,0x43,0x6c,0x61,0x73,0x73,0x69,0x63,0x20,0x56,0x69,0x65,0x77
  SubSecTime: 00
  ...
  ImageUniqueID: 090caaf2c085f3e102513b24750041aa
546 rmills@rmillsm1:~/temp $ 
```

I've investigate the warning about 0x8830:

```bash
546 rmills@rmillsm1:~/temp $ taglist ALL | csv - | grep 0x8830
[Photo.SensitivityType]	[34864]	[0x8830]	[Photo]	[Exif.Photo.SensitivityType]	[Short]	[The SensitivityType tag indicates which one of the parameters of ISO12232 is the PhotographicSensitivity tag. Although it is an optional tag, it should be recorded when a PhotographicSensitivity tag is recorded. Value = 4, 5, 6, or 7 may be used in case that the values of plural parameters are the same.]	
547 rmills@rmillsm1:~/temp $ 
```

Support for that tag was added by Luis in 2018.  That tags is in the Exif 2.3 Specification.

**Comment by butcherg** [comment] 2021-02-06 20:47
> I'm a little surprised by your comment that _exiv2 was writing metadata to a TIFF that when later read by libtiff was not palatable_.

To be clear, I did it to myself.  I thought after I found the first tag in my search, I was good to go.  Goofball application programmer, am I... :D

**Comment by kmilos** [comment] 2021-02-06 20:57
> Goofball application programmer, am I... :D

Lazy vs greedy search ;)

**Comment by clanmills** [comment] 2021-02-06 22:07
I'm quite certain that you're not a goofball, my friend.

**Comment by butcherg** [comment] 2021-02-06 22:12
> I'm quite certain that you're not a goofball, my friend.

You must converse with my wife...  :D
