### ISSUE TITLE
Exiv2 v0.27.3: versionString() function return 0.27.2

### ISSUE THREAD

**Issue by philvl** [Exiv2/exiv2#1240] opened 2020-07-06 23:55 UTC
Hello,

I would like to report a small mistake: under Linux, the Exiv2::versionString() function of Exiv2 v0.27.3 returns wrong information: "0.27.2".

Thanks to the whole development team.
Regards,

**Comment by clanmills** [comment] 2020-07-07 07:00
@philvl Thank You for reporting this.  I discovered this on Monday 2020-06-29 when I had a "dry run" for the 0.27.3 release which I built on Tuesday 2020-06-30.

The problem's being caused by the CMake code.  It's picking up exv_conf.h from /usr/local/include/exiv2.  It shouldn't.  It should be using the one generated in `<exiv2>/build` by CMake.  So the fix is:

```
$ cd <exiv2>
$ rm -rf /usr/local/include/exiv2
$ rm -rf build ; mkdir build ; cd build
$ cmake ..
$ make
$ sudo make install
```

Let me know how that works for you.

I suspect things have been in this state for years.  When I hear back from you, I'll investigate why CMake is using the wrong include file.

The whole development team is me and the cat.  Dan and Luis are working on 0.28.  Progress is glacial.  Kevin occasionally helps with security.   The community contribute to Exiv2 by sending frequent abusive emails and criticism.

I'm writing a book about Exiv2.  Have a look at Chapter 13:  https://clanmills.com/exiv2/book/#13

**Comment by philvl** [comment] 2020-07-07 18:01
Hello @clanmills, 

I made two different tests:
**The first one**: 
I download and compile Exiv2 0v27.3 sources on a fresh system (a system where exiv2 has never been installed) -> versionString() return 0.27.3 => OK!

**The second one**: 
I download and compile Exiv2 0v27.2 sources on a fresh system -> versionString return 0.27.2.
Then I download and compile Exiv2 0v27.3, and versionString return the good value : 0.27.3

**Conclusion**
I can't reproduce the bug on my system (Linux Mint 20). When I opened the ticket yesturday, I used directly the Linux library already compiled in the zip file available on the Exiv2 site. The library inside the zip files mays a "broken" Exiv2 version.

I read chapter 13, and I think I'll read the whole book when I have a little time, your vision is very realist and I like your writing style and your humor.

See you ;-)

**Comment by clanmills** [comment] 2020-07-07 19:40
Thanks @philvl.  If you're happy, can you close this issue, please.

I looked at the CMake code today.  It appear to set the -I compiler flags correctly.  However, there's little doubt that this is "pollution" from an earlier release being on the system.

I've had a very busy day and didn't get to fixing the web-site yet.  I will fix it of course.  It's on the list!

**Closed** 2020-07-07 22:01 UTC
Labels: Compilers
