### ISSUE TITLE
Conan recipe is generating package for older version of libexiv2

### ISSUE THREAD

**Issue by AhiyaHiya** [Exiv2/exiv2#1991] opened 2021-10-31 19:42 UTC
##### **Describe the bug**
Unable to get the latest stable version of libExiv2, when using conan to deliver the package.

##### **Notes**
Using conan to download libexiv2 package, version exiv2/0.27.4, as listed on `https://conan.io/center/exiv2`.
Created small sample project to call Exiv2. Compiler returned error that `auto_ptr` is not a member of `std`.
The error was traced to file `value.hpp`, in folder `C:\Users\username\.conan\data\exiv2\0.27.4\_\_\package\feb82ed54abc17b65ba05c47e8db7e1d9180d291\include\exiv2\value.hpp`
Researching `auto_ptr`, it appears that `auto_ptr` was replaced in version v0.27.3 of libexiv2. However, the source that is in `~/.conan` appears to be older code.

##### **To Reproduce**
Sample project available at https://github.com/AhiyaHiya/media_helpers_cli 
Use branch `feature/update_code_for_conan`
You can use the following command to build with CMake: the ConanHelper.cmake module will download the packages as needed:
`cmake -S . -B build`
Open up the project/solution under `build` and attempt to compile project.

##### **Expected behavior**
Expected to get v0.27.4 version of libExiv2.

##### **Desktop (please complete the following information):**
- OS and version: macOS Catalina, Windows 10
- Compiler and version: clang, xcode 11, Visual Studio 2019

##### **Additional context**
I tested this under Windows 10 and macOS Catalina.
On both operating systems, I used pip to install conan.
I removed conan from pip as a test, and also deleted the .conan folder.
I got the same results on both operating systems, even with removing and reinstalling conan.

**Comment by clanmills** [comment] 2021-11-21 14:13
@AhiyaHiya I'm surprised that nobody has replied to this issue.

I don't think this is an Exiv2 issue.  I think you'll have to report this issue to whoever supports/authored/owns the Exiv2 Conan recipe.  

`auto-ptr` is a C++98 feature and is used by every released version of Exiv2, including the latest 0.27.5 which shipped on 2021-10-22.

C++11 and C++14 can compile `auto-ptr` using some compatibility magic.  The preferred approach is replace `auto_ptr` with `unique_ptr` and this has been done on the `main` branch.  You will not be able to build `main` with C++98.

The recipe should build using `-DCMAKE_CXX_STANDARD=98` or 11 or 14.  If `-DCMAKE_CXX_STANDARD` is not specified, I'm not sure what CMake does.  However if it defaults to 17 or 20, the 0.27-maintenance code will not build.

If the build uses 11 or 14, the compiler will issue an avalanche or warnings concerning `auto_ptr`.  These can be suppressed with the following options (as documented in README.md).

```
$ cmake .. -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_FLAGS=-Wno-deprecated
```

I wish you success in getting this fixed as I'm sure this is causing inconvenience to other users.

**Comment by clanmills** [comment] 2021-11-21 14:20
The Team Exiv2 CMake expert is @piponazo.  Luis can you comment on this please?

**Comment by piponazo** [comment] 2021-11-21 17:17
Hi. I'll take a look to the issue and try to determine what's going on there.

There is something I would like to highlight now anyways. The conan recipe seems to be maintained by the conan community and we did not participate there (at least not me). One can also report issues about existing recipes here:
https://github.com/conan-io/conan-center-index

**Comment by piponazo** [comment] 2021-11-21 17:23
I've tried to reproduce the error on Linux but the CMake call fails with this error on the `media_helpers_cli` project:
```
-- Detecting CXX compile features - done
-- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
CMake Error at ConanHelper.cmake:12 (file):
  file DOWNLOAD HASH mismatch

    for file: [/media/linuxDev/programming/media_helpers_cli/buildRelease/conan.cmake]
      expected hash: [855c95e546dcaf0538369e8a6dfa37e219cb9be2f9523eb2119755ebee8eef4f]
        actual hash: [8e1ae613d112105fcb43f2837fe81d6d08b4619237a8035731afebbea9646e32]
             status: [0;"No error"]

Call Stack (most recent call first):
  CMakeLists.txt:17 (include)
```
I will try to check the issue with a different setup.

**Comment by piponazo** [comment] 2021-11-21 17:44
After re-reading the conversation & checking the conan recipe for exiv2 0.27.4 (which it looks correctly implemented) I think the ball is on @AhiyaHiya side.

As @clanmills commented, `auto-ptr` is still present on the 0.27 releases. This should not be a problem thought, unless you use C++17 or higher. auto_ptr was marked as deprecated since C++11 but not removed until C++17:
https://devblogs.microsoft.com/cppblog/c17-feature-removals-and-deprecations/

Also, as @clanmills suggested, you can get around this issue by turning off the deprecation warnings if you use C++11 or 14 by turning deprecation warnings off
```
$ cmake .. -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_FLAGS=-Wno-deprecated
$ cmake .. -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_FLAGS=-Wno-deprecated
```
It looks like you should also be able to turn deprecation warnings on MSVC (although I never tried that by myself):
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170

In the `main` branch the `auto_ptr` code has been already replaced my the newer smart pointer introduced in C++11. However, there is not a release of Exiv2 1.0 yet.

Please, let us know if the suggestions provided here help somehow.

**Comment by clanmills** [comment] 2021-11-21 19:56
I've reproduced the error mentioned by @piponazo on macOS (Catalina, x86, Xcode 12.1 CMake 3.22.0).

```
CMake Error at ConanHelper.cmake:12 (file):
  file DOWNLOAD HASH mismatch
```

Here's the CMakeLists.txt code in media_helpers_cli.  I'm not sure what this has to do with Exiv2.  It's demanding C++17.

```
718 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli/build $ cat ../CMakeLists.txt 
cmake_minimum_required(VERSION 3.19)

project(media_helpers_cli VERSION 0.1.0)

# C++17
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Folders for IDEs that support it
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

# We need to specify these types since we are supporting multi-config IDEs like Xcode and Visual Studio
list(APPEND CMAKE_CONFIGURATION_TYPES "Debug" "Release")

######################################################################
# Conan helper to download required files
include(ConanHelper.cmake)

conan_cmake_run(CONANFILE conanfile.txt
                BASIC_SETUP CMAKE_TARGETS
                BUILD missing)

include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)

######################################################################
# Application
add_executable(organize_media organize_media/main.cpp)

target_link_libraries(organize_media
  PRIVATE
    CONAN_PKG::boost
)
719 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli/build $ 
```

**Comment by clanmills** [comment] 2021-11-21 20:06
Are your sure Exiv2 is involved with media_helpers_cli?

```bash
728 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ find . -name "*pp" -print0 | xargs grep -vl include
./organize_media/main.cpp
729 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ find . -name "*pp" -print0 | xargs grep include
#include <filesystem>
#include <iostream>
#include <boost/program_options.hpp>
#include <libraw/libraw.h>
#include <vips/vips.h>
730 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ $ find . -name "*pp" -print0 | xargs grep exiv2
731 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ 
```

**Comment by clanmills** [comment] 2021-11-23 20:44
I'm going to close this as there doesn't seem to be a case to answer.  @AhiyaHiya If you learn more about this matter, please update this issue and it will be reopened and investigated.

**Closed by clanmills** 2021-11-23 20:44 UTC
Labels: bug

**Comment by AhiyaHiya** [comment] 2021-11-24 04:47
> Are your sure Exiv2 is involved with media_helpers_cli?
> 
> ```shell
> 728 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ find . -name "*pp" -print0 | xargs grep -vl include
> ./organize_media/main.cpp
> 729 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ find . -name "*pp" -print0 | xargs grep include
> #include <filesystem>
> #include <iostream>
> #include <boost/program_options.hpp>
> #include <libraw/libraw.h>
> #include <vips/vips.h>
> 730 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ $ find . -name "*pp" -print0 | xargs grep exiv2
> 731 rmills@rmillsmm-local:~/gnu/github/media_helpers_cli $ 
> ```

With regard to the above question, I placed the sample Exiv2 code into files.cpp:

```
// System
#include <iostream>

// Third party
#include <exiv2/exiv2.hpp>

// Project
#include "files.h"

namespace fs = std::filesystem;

ExifHelper::ExifHelper() { Exiv2::XmpParser::initialize(); }

ExifHelper::~ExifHelper() { Exiv2::XmpParser::terminate(); }
```

**Comment by AhiyaHiya** [comment] 2021-11-24 04:57
> I've tried to reproduce the error on Linux but the CMake call fails with this error on the `media_helpers_cli` project:
> 
> ```
> -- Detecting CXX compile features - done
> -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
> CMake Error at ConanHelper.cmake:12 (file):
>   file DOWNLOAD HASH mismatch
> 
>     for file: [/media/linuxDev/programming/media_helpers_cli/buildRelease/conan.cmake]
>       expected hash: [855c95e546dcaf0538369e8a6dfa37e219cb9be2f9523eb2119755ebee8eef4f]
>         actual hash: [8e1ae613d112105fcb43f2837fe81d6d08b4619237a8035731afebbea9646e32]
>              status: [0;"No error"]
> 
> Call Stack (most recent call first):
>   CMakeLists.txt:17 (include)
> ```
> 
> I will try to check the issue with a different setup.

(cc @clanmills )
With regard to the above error, this is happening because the `ConanHelper.cmake` module is pulling the `conan.cmake` from develop: https://github.com/conan-io/cmake-conan/issues/336

Sorry if the above error confused anyone. This is one of the joys of dealing with code off of the develop branch.

Updating the hash removed the error message emitted by the CMake config process.

**Original issue**
Now back to the original issue, which is that I'm seeing an earlier version of Exiv2 produced by the Conan recipe.

It sounds like I may have to create a ticket over at conan.io.

Thanks for your time.

**Comment by piponazo** [comment] 2021-11-24 06:51
Hi @AhiyaHiya ,

Please note that you are also requiring C++17 in your project:

```
set(CMAKE_CXX_STANDARD 17)
```
And it will be not-compatible with the Exiv2 0.27.X releases as we explained before. If C++17 is not a "MUST" for you, please consider to user C++14. Otherwise, consider to use Exiv2 from master (where `auto_ptr` was replaced already)

**Comment by AhiyaHiya** [comment] 2021-11-24 16:58
That is a good point.

I will hold off on reporting the conan recipe.

Thanks again.
