### ISSUE TITLE
Please consider adding the feature of exporting cmake targets 

### ISSUE THREAD

**Issue by jasjuang** [Exiv2/exiv2#86] opened 2017-09-30 22:53 UTC
Please consider adding the feature of exporting cmake targets as described in [here](
https://cmake.org/cmake/help/v3.9/command/install.html#installing-targets). These feature will generate a `exiv2-config.cmake` or `exiv2Config.cmake` that allows the developers to use `find_package(exiv2)`  in their downstream project in config mode as described in [here](https://cmake.org/cmake/help/v3.9/command/find_package.html) so they don't have to write their own `FindEXIV2.cmake`.

**Comment by clanmills** [comment] 2017-10-01 01:15
Jason.  I've assigned this to @piponazo who is the team's CMake expert.

**Comment by piponazo** [comment] 2017-10-01 06:12
Hi Jason, thanks for reporting this. I think I tried to add this feature and there was something about the current autotools design that block me to do it. Currently we are maintaining both configuration systems, and sometimes it is not easy to apply a change in cmake without breaking things in the autotools.

I will revisit this point ASAP and I will let you know if it's feasible to implement this feature fit the next 0.26.1 release. ;)

**Comment by clanmills** [comment] 2017-10-01 08:41
Jason and Luis:  Thanks for your work on this.  I own the Exiv2 autotools support and will investigate.

Jason:
Thanks for agreeing to work with us on vcpkg support in v0.26.1  Let's work together to ensure v0.26.1 fixes all your concerns.  The v0.26.1 release was intended to be a minor effort.  However the scope has extended and I have just started a 2 month trip away from home.  I hope we'll achieve v0.26.1 RC1 in December and GM early 2018.

**Comment by Kicer86** [comment] 2017-10-01 13:34
@clanmills do we still need autotools?

**Comment by piponazo** [comment] 2017-10-01 14:44
@Kicer86 I asked him the same question few weeks ago :). The idea is to keep everything as it is for 0.26.1, while we try to improve the CMake support. Afterwards, for the next stable version, I will propose deeper changes in the code base that could break the autotools support. In that case we could deprecate the autotools and just focus in the CMake code, if we can guarantee that we can build Exiv2 in all the platforms that the autotools do it nowadays.

I am in favour of just maintaining one system (CMake) instead of keeping the support for the mix of approaches we are maintaining today (autotools, cmake, Visual Studio Solution files ...)

**Comment by piponazo** [comment] 2017-10-01 15:54
I am investigating a bit and it seems that it is possible to add this feature without breaking things in the autotools part.

@jasjuang I will create a Pull Request soon so you can check my branch and test the final implementation ;)

**Comment by clanmills** [comment] 2017-10-01 20:16
Yes.  We don’t know anything about users build scripts.  We should announce our intention to deprecate autotools before doing so.

Additionally, I am still working on C++11 support.  And I’m working on support for Adobe’s XMPsdks (2013/2014/2016).  The plan is to get those features working correctly with autotools and msvc/, then modify CMake appropriately.

I am unwilling to remove either autotools or msvc/ support until:

1 We have given fair notice that we intend to deprecate those environments.

2 We are have 100% confidence that CMake support builds Exiv2 really well.

I use CMake/Xcode to develop Exiv2.  So I am close to feeling OK about CMake being a replacement for autotools on MacOS-X, Cygwin and Linux.

I have little confidence in CMake/Visual Studio as a replacement for our msvc/ solution & project files.  CMake/Visual Studio dependency support is awful. I have high hopes of Conan to address that, however It is too early to be adopted as our only build support for Visual Studio.

Robin
http://clanmills.com
Not sent from my iPhone

**Closed** 2017-10-02 09:39 UTC
