### ISSUE TITLE
Migration to C++11

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#214] opened 2018-01-15 22:06 UTC
@clanmills suggested in #46 that we should move to C++11 for 0.27.

Things we should consider before the move:
1. For which platforms will we drop support by that? C++11 is fully supported by gcc >= 4.8.1, clang >= 3.3 and msvc probably >= 2015 (msvc supports some features already since 2010, but some like noexcept, are not supported by msvc < 2015).
2. Are all our dependencies compatible with C++11? expat, zlib, curl, libssh are written in C, so they are fine. I am however not sure about the XMP SDK. I haven't found any information about this and thus I am afraid this will be more work.
3. Will this be a problem for projects using exiv2? The KDE & GNOME projects both use exiv2. Afaik KDE uses C++11, GNOME maybe too? Anyway, we should probably ask a bit around before moving on, as we don't want projects using 0.26 for longer than necessary

 Here is my list what we should do for C++11 support:

- [x] drop `auto_ptr` and replace it with `unique_ptr` or `shared_ptr` (see #257)
- [x] replace the current method how we prevent some classes from being copied (declare a private copy constructor & `operator=()`) with the `classname(const classname&) = delete` (and the same for the move constructor) (see #697)
- [x] remove any `throw()` or `throw(something_t)` from the code and replace the former with `noexcept`, generally we should add `noexcept` to all functions that will not throw
- [ ] make some constructors `constexpr` & introduce `static_assert` where applicable
- [x] Use `nullptr` instead of `NULL`
- [ ] Switch to the using directive for inherited functions (especially in `slices.hpp`)
- [ ] Introduce variadic templates where appropriate (`enforce.hpp`, Constructors of `BasicError`)

**Comment by D4N** [comment] 2018-01-15 22:31
Concerning the platform support, here is the current situation for the most popular Linux distros from distrowatch (excluding derivates & rolling release like Arch & Gentoo):
- Ubuntu <= 13.04 (not an issue, 12.04 LTS reached eol last year)
- Fedora <= 18 (not an issue, not supported for a long time anymore)
- elementary <= 0.2 (don't know if that is still supported)
- OpenSUSE <= 12.3 (not an issue, already reached eol)
- CentOS <= 6 (6 will reach eol in 2020)
- Linux Mint <= 15 (not an issue, reached eol in 2014)
- Debian <= 7 (7 will reach eol in May 2018)
- PCLinuxOS <= 2014.12
- Mageia <= 3 (reached eol in 2014)

So probably the only problem will be the derivatives of RHEL 6 (like CentOS), which do not have a recent enough gcc to support building with all C++11 features, however a subset of the features is already available. Imho it is not worth hanging on to C++98 just for RHEL 6, since most admins are probably already migrating to RHEL 7.

Could someone take a look at Windows & OSX? And what's the situation with the BSDs?

**Comment by clanmills** [comment] 2018-01-15 23:31
I think your proposal is fine.

The "core" of Exiv2  is in v0.26 and supports most metadata read/write/modify operations.  So, for folks using elderly build systems, they probably will be stuck with v0.26.  Many of the security features have been ported into patches for v0.26. 
 
I would like to make an announcement about our plans for v0.27 on https://discuss.pixls.us and request user input.  If folks want us to continue build support for VS2005, or Free BSD, or MacOS-X Tiger, they should discuss their platform with us.

I'd like the announcement to say that we will have a "Exiv2 Developer's Meeting" at which the team can agree on what's going into v0.27 and the schedule.  At the moment, I'm sitting in England wondering how to co-ordinate the project to reach an agreed goal.

**Comment by Kicer86** [comment] 2018-01-16 08:59
I was investigating auto_ptr to unique_ptr switch and there are two places which are troublesome. I'll search for it later.

**Comment by clanmills** [comment] 2018-01-16 12:21
About the Adobe XMPsdk.  There are four versions:
2016 and 2014 build with C++11
2013 and the "ancient old source code in the exiv2 tree", I think they build with C++98.

We can move to C++11 and adopt XMPsdk 2014 and later.

**Comment by Kicer86** [comment] 2018-01-16 19:05
Problematic funcions: TiffDirectory::doAddPath (in two from a few overloads) - see how 'object' travels

**Comment by clanmills** [comment] 2018-01-16 20:36
@Kicer86   What's the problem with TiffDirectory::doAddPath() and C++11?

**Comment by Kicer86** [comment] 2018-01-17 19:48
Actually is has nothing to do with c++11. There just some places where auto_ptr is being copied (or moved) twice. I'm not sure if it is intentional or if it is a bug.

**Comment by Kicer86** [comment] 2018-01-17 19:54
Replacing auto_ptr with unique_ptr will work the same way, but maybe its a good time to check it.

**Comment by clanmills** [comment] 2018-01-17 21:03
The TiffMumble classes are difficult to understand.  However, the code is robust.  It has stood the test of time.  I can hardly remember a bug being reported in that code.  I'm glad it's so robust as fixing/changing it would be challenging.  The code is recursive and I'm sure passes auto_ptr down the recursion tree.  Can you try replacing auto_ptr with unique_ptr and see where that leads?

Sometime last year, I tried changing all auto_ptr in the code to exiv2_ptr and using a macro to convert exiv2_ptr to auto_ptr for C++98 and unique_ptr for C++11.  I didn't have any success with this, although I can't remember why this refused to work.  Perhaps auto_ptr and unique_ptr are keywords in C++ or something like that.

**Comment by D4N** [comment] 2018-01-17 21:52
My guess would be the different behavior of auto_ptr vs unique_ptr. When
auto_ptr is assigned via = it creates a copy & transfers ownership,
whereas unique_ptr only transfers ownership to the new variable and
deletes the old one. The code might rely on the "original" still
existing, but I am just speculating.

**Comment by clanmills** [comment] 2018-01-18 08:04
Yes.  There could be difficulties.  https://stackoverflow.com/questions/3451099/stdauto-ptr-to-stdunique-ptr

We're going to have to really investigate this.  We might be fortunate and unique_ptr is a "pain free" replacement in Exiv2.

At the moment, I can build with C++11 and suppress the deprecation warnings about auto_ptr in order to build with Adobe XMPsdk (2013/2014/2016).  I believe we all want to bury C++98 and stop using auto_ptr.

**Comment by D4N** [comment] 2018-01-22 22:47
I have taken a look at the code @Kicer86 mentioned ([src/tiffcomposite_int.cpp:649](https://github.com/Exiv2/exiv2/blob/master/src/tiffcomposite_int.cpp#L649)) and at least one of the issues is, that a new `auto_ptr` is created in line 674, which may or may not become the parameter `object` (which is passed to the function `TiffDirectory::doAddPath` itself). However `atc` is saved via `addNext` and `object` is returned.

This is not possible with `unique_ptr`, which forbids copies, you can only move the pointer (thereby transferring ownership). Depending on what the code actually does, we have to either make a copy here explicitly or use `shared_ptr` if both pointers (`atc` and `object`) can point to the same object.

**Comment by Kicer86** [comment] 2018-01-31 20:57
@D4N the same happens for auto_ptr now. There is a silent move.

**Comment by D4N** [comment] 2018-02-01 21:35
Ah, yes, you are right. I must admit I never worked with auto_ptr, so my knowledge of it is rather limited.

So, that is kind of good, as then the only necessary change is to add a `std::move`. However we should also recheck the aforementioned function, in case that branch where ownership is transferred was overlooked.

**Comment by piponazo** [comment] 2018-04-01 17:25
I did not read all the details about the issue yet, but I want to state something about `std::auto_ptr`. Its usage was considered deprecated since c++11, and it will be removed in future versions of the standard (I've read that this will be the case with c++17, but I am not 100% sure). That means, if we do not remove `auto_ptr` from the public headers, clients using modern standards (c++17, 20, etc) could have problems with it.

On the other hand, if we replace it by `std::unique_ptr` we will force to our clients to use a compiler with c++11 support. 

If we could find a way to not use any of them, maybe we could still support old and modern c++. However, if this is too much work, for me it would make more sense to move to the new modern standards ASAP.

**Comment by D4N** [comment] 2018-04-02 10:34
`auto_ptr` is deprecated since C++11 and has been removed in C++17, see [cppreference.com](http://en.cppreference.com/w/cpp/memory/auto_ptr). So yes, you cannot use exiv2 if you want to compile your project with C++17. And you are right too, that by switching to `unique_ptr` we'll force clients to update.

I am against having a dual-standard code base. I have a project at work where I have to do that, and let me tell you: it sucks. I have so many macros that try to work around features of C++>11 not being in C++03 and in the end you still can only use a small subset of the C++11 features, because it is impossible to emulate them in C++03. In the one has to use C++03 anyway plus the additional work of keeping the codebase compatible.

I agree with you, that we should move to C++11. It's 2018 and C++11 has been the new standard for 7 years and it was planned for over 10. It is already the default in most compilers and afaik visual studio cannot even compile pure c++03 any more?

**Comment by piponazo** [comment] 2018-11-06 16:10
Hi guys. 

Since we are close to release v0.27 and finally we could take care of this issue, I wanted to raise a question here: Should we switch to **c++11** or **c++14**?. I would say that c++17 is out of the question because the compiler version provided by some linux distributions probably are not fully C++17 compatible. 

In C++14 there was only minor improvements, fixes and additions respect to C++11, but it would be interesting to be able to use some of them:

https://github.com/AnthonyCalandra/modern-cpp-features

I would propose to try to move directly to C++14 and check if the compilers used in the distributions we are testing (via Appveyor and Gitlab) can handle this standard. Otherwise, it's fine to restrict ourselves to C++11.

**Comment by clanmills** [comment] 2018-11-06 16:26
I don't think we should move to C++17.  That's a big step.  C++11 or C++14?  You choose.

Remember that the plan for v0.27 is LTS (long term support).  So I hope to have regular "dot" releases over the next couple of years.  Folks on C++98 systems will continue to get security updates for a couple of years.

**Comment by cgilles** [comment] 2018-11-06 16:27
Luis,

I respond immedialty here : C++11, not yet C++14.

KDE project with KF5 libraries (a monster written in C++/Qt), switch only
to C++11 for the moment, to be portable everywhere.
The mostly reason are :

- G++ compiler was mostly stabilized at least to 5.5.x in main Linux distro.
- 32 bits supports require C+11, especially with MinGW. Look like MXE cross
compiler use G++ 5.5 inside...
- Clang under MacOS work fine with C++11. I see dysfunction to compile KF5
under my Macbook pro.
- M$ Visual C++ which is later to support recent C++ standard. It's the
hell (as usual with M$), even if last Visual C++ improve the C++ standard
support...

Personalty, with all my C++ projects (open source and in my office), where
code must be portable everywhere, C++11 pass everywhere.
C++14 still a little bit problematic.

Before to port code to C++11, I recommend to and stabilize the current
implementation first, using static analyzers. Fix all reports from static
analyzers, and only port to C++11. For each main code change run the
analyzers, and check the regressions. It's my safe approach to deal with
digiKam source code (1.2M lines of code)...

Best
Gilles Caulier


Le mar. 6 nov. 2018 à 17:10, Luis Díaz Más <notifications@github.com> a
écrit :

**Comment by piponazo** [comment] 2018-11-06 16:42
Thanks @cgilles for your feedback, I think it will be useful for us to not make mistakes. 

I will take your advise and spend some time with static analysers before moving to C++11.

**Comment by adithyabhat99** [comment] 2019-04-23 15:22
hope you guys release support for cpp11 soon
 auto_ptr being depreciated in cpp11 is causing problems

**Comment by adithyabhat99** [comment] 2019-04-23 15:26
for the issue with auto ptr depreciation in cpp11 , add these lines on top of every file included in the package

#if __cplusplus >= 201103L
template <typename T>
using auto_ptr = std::unique_ptr<T>;
#else
using std::auto_ptr;
#endif

**Comment by D4N** [comment] 2019-04-23 19:08
> for the issue with auto ptr depreciation in cpp11 , add these lines on top of every file included in the package

If you **really** need C++ >= 11 support, then you'll have to rely on the Exiv2 master branch, as the current release still maintains C++98 compatibility.

Note though that the deprecation of `auto_ptr` is only a problem if you absolutely require C++17, as `auto_ptr` got removed there, for C++11 and 14 you'll only get a warning.

**Comment by clanmills** [comment] 2021-04-13 14:16
This is the number 1 feature for v1.00.

**Closed by clanmills** 2021-04-13 14:16 UTC
