### ISSUE TITLE
[0.27.0] The tarball on exiv2.org contains macosx files which get installed

### ISSUE THREAD

**Issue by cryptomilk** [Exiv2/exiv2#627] opened 2019-01-02 10:00 UTC
Hi,

the tarball http://exiv2.org/builds/exiv2-0.27.0-Source.tar.gz contains hidden MacOSX files. As you're using globbing to install the install headers the macosx files get installed too.

a) Do not use globbing
b) Do not add hidden macosx files to tarballs

**Comment by cryptomilk** [comment] 2019-01-02 10:06
CPack has support for generating package source files including tarballs. If you don't use that yet, you should take a look at https://cliutils.gitlab.io/modern-cmake/chapters/install/packaging.html

**Comment by cryptomilk** [comment] 2019-01-02 10:15
FYI: https://build.opensuse.org/request/show/662405

**Comment by clanmills** [comment] 2019-01-02 10:32
Happy New Year, Andreas.  Yes, we're using CPack to build the bundles.  In v0.26, I had my own script and was able to add `export DISABLE_COPYFILE=1` to fix this on MacOS-X.  CPack is creating the tar.gz with those hidden files and doesn't respect DISABLE_COPYFILE.  So this issue has resurfaced because we adopted CPack.

I've been thinking about this quite a lot.  I'm going to build source bundles on Linux in future.

Today, I'll create a new source bundle manually to remove the hidden files and update the sha256sum on the website.  I'll request Suse to delay publishing the tar-ball with the hidden files.

**Comment by D4N** [comment] 2019-01-02 10:43
This is a duplicate of #620

**Closed by D4N** 2019-01-02 10:43 UTC

**Comment by cryptomilk** [comment] 2019-01-02 18:30
Happy new year Robin!

**Comment by clanmills** [comment] 2019-01-02 20:22
And Happy New Year to you and your lady, Andreas.

Thanks for bringing up this subject.  It has been sitting on my TODO list for a few days as it was reported last week.  I've done something about #620 and hope to close it tomorrow.

The other matters that you raised today are interesting/curious and obvious candidates for v0.27.1 which is scheduled for 31 March 2019.

I was hoping to have less work and stress in 2019.  Clearly not!  On the other hand, Exiv2 keeps my brain busy and active.  I was reading on New Year's Eve that the last Professor Stephen Hawking's Rule 1 was _**never give up working**_.  He's right.
