### ISSUE TITLE
FAIL: test_run (github.test_issue_2427.issue_2427_BmffImage_brotliUncompress_memleak.test_run

### ISSUE THREAD

**Issue by norbertwg** [Exiv2/exiv2#2788] opened 2023-10-02 15:02 UTC
Some of the checks fail in my pull requests. Local tests with `ctest -C Release --test-dir build --output-on-failure` and `python3 runner.py` complete successfully. I also do not find the test in test folder, so I was not able to search for the root cause of this failure. Anyhow I am pretty sure, that this failure is not related to my code changes (e.g. adding two lenses in nikonmn_int.cpp). 

Here the output:

```
======================================================================
FAIL: test_run (github.test_issue_2427.issue_2427_BmffImage_brotliUncompress_memleak.test_run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/exiv2/exiv2/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/Users/runner/work/exiv2/exiv2/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/Users/runner/work/exiv2/exiv2/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Exiv[61 chars]/exiv2/test/data/issue_2427_poc.jpg:\n_ERROR_FORMAT_CL_SPACE\n' != 'Exiv[61 chars]/exiv2/test/data/issue_2427_poc.jpg:\nCL_SPACE\n'
  Exiv2 exception in print action for file /Users/runner/work/exiv2/exiv2/test/data/issue_2427_poc.jpg:
- _ERROR_FORMAT_CL_SPACE
+ CL_SPACE
 : Standard error does not match
````

**Comment by kmilos** [comment] 2023-10-02 16:05
Duplicate of https://github.com/Exiv2/exiv2/pull/2762 and https://github.com/Exiv2/exiv2/issues/2763

Please search before opening new issues.

**Closed by kmilos** 2023-10-02 16:05 UTC

**Comment by norbertwg** [comment] 2023-10-02 18:18
Sorry, but from descriptions in #2762 and #2763, I did not see, that they are describing the same problem.

**Comment by neheb** [comment] 2023-10-13 02:16
both describe the same. The problem is upstream changing the error code. Needs to be handled or disabled in the test suite.
