### ISSUE TITLE
infinite loop in CR2 file, resembles #51

### ISSUE THREAD

**Issue by potuz** [Exiv2/exiv2#156] opened 2017-11-07 19:45 UTC
Attaching a zip file with the CR2 file that triggers this issue. Running in gdb find that I'm stuck in `Image::printIFDStructure` inside the `do {  } while(start);` loop. 

A bt on gdb is
```
 #0  Exiv2::Image::printIFDStructure (this=this@entry=0x647a90, io=..., out=..., 
    option=option@entry=Exiv2::kpsRecursive, start=16515072, start@entry=700, 
    bSwap=bSwap@entry=false, c=<optimized out>, depth=2)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/image.cpp:352
#1  0x00007ffff7a332ae in Exiv2::Image::printIFDStructure (this=this@entry=0x647a90, 
    io=..., out=..., option=option@entry=Exiv2::kpsRecursive, start=270, 
    bSwap=bSwap@entry=false, c=<optimized out>, depth=1)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/image.cpp:481
#2  0x00007ffff7a32cba in Exiv2::Image::printIFDStructure (this=this@entry=0x647a90, 
    io=..., out=..., option=option@entry=Exiv2::kpsRecursive, start=16, 
    bSwap=bSwap@entry=false, c=<optimized out>, depth=0)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/image.cpp:451
#3  0x00007ffff7a33735 in Exiv2::Image::printTiffStructure (this=this@entry=0x647a90, 
    io=..., out=..., option=option@entry=Exiv2::kpsRecursive, depth=depth@entry=-1, 
    offset=offset@entry=0)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/image.cpp:523
#4  0x00007ffff7a01746 in Exiv2::Cr2Image::printStructure (this=0x647a90, out=..., 
    option=Exiv2::kpsRecursive, depth=0)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/cr2image.cpp:86
#5  0x00007ffff7a0198a in Exiv2::Cr2Image::readMetadata (this=0x647a90)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/cr2image.cpp:111
#6  0x000000000041f591 in Action::Print::printSummary (this=this@entry=0x648c00)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/actions.cpp:289
#7  0x0000000000421868 in Action::Print::run (this=0x648c00, 
    path="Pictures/2006/05/05/IMG_0186.CR2")
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/actions.cpp:244
#8  0x000000000040af26 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/media-gfx/exiv2-0.26_p20171104/exiv2-0.26_p20171104/src/exiv2.cpp:170
```
It's the same loop referred to in #51 but the patch is already there in 0.26.

**Comment by potuz** [comment] 2017-11-07 19:48
[IMG_0186.CR2.zip](https://github.com/Exiv2/exiv2/files/1451391/IMG_0186.CR2.zip)

**Comment by D4N** [comment] 2017-11-07 19:56
Thanks for the report!
Did you happen to find this with AFL? And is this an issue on 0.26 or on master?

**Comment by potuz** [comment] 2017-11-07 20:02
Nope just compiled digiKam on gentoo to try to import my photo library and noticed that hung on some CR2 files. Tracked the issue to exiv2 and surprisingly not all my CR2 files trigger this issue. Ran on gdb and found that I'm stuck in that loop, but not knowing the code I'm out of my depth to try to solve this myself. It's 0.26 on gentoo, the package is p20171104 so I suppose it includes patches for some of the latest CVEs.

**Comment by D4N** [comment] 2017-11-07 20:59
I'll take a look at this.

**Comment by potuz** [comment] 2017-11-07 21:04
Thanks!

**Comment by D4N** [comment] 2017-11-08 00:20
Ok, this seems to be a trickier problem than I thought. @clanmills could you take a look at this?

Here is what I found out:
The hang occurs in `printIFDStructure` because `start` is never set to 0 after the IFD starting at `0x2BC` (thus the do-while loop never terminates).
The problematic IFD has 24 directories and ends at `0x3DE` (=990 = 0x2BC + 2 (dir length) + 12*24), here is the hexdump of the end:
```
000003d0: 0000 0340 0300 1600 0000 1c23 0000 8004  ...@.......#....
000003e0: 0000 0000 5c00 0200 0000 0400 0000 0000  ....\...........
```
`printIFDStructure` now reads the next four bytes (`0x80`, `0x04`, `0x00`, `0x00`) and calculates the offset from them resulting in `0x480`. The hexdump of that address is:
```
00000480: 0000 0000 fc00 0000 ffff 0000 0000 0000  ................
```
The directory length is zero, thus `printIFDStructure` reads the next four bytes (`0x00`, `0x00`, `0xFC`, `0x00`) and interprets this as the offset `0xFC0000` which is outside of the file. At this point after calling `io.seek` we are outside of the image and any consecutive calls to `read` result in no read (thus we re-set start to the offset `0xFC0000`) and result in an endless loop.

There are multiple things that we could do here:
- `io.seek` and `io.read` aren't checked for errors (`seek` actually does not complain, as we probably have to use `ferror` to check, but `fread` returns 0 indicating that nothing was read).
- `start` must not be larger than `io.size()` otherwise something is wrong

However, I don't understand really the issue here. The file is an ordinary image (not a crafted input) but the IFD is not properly terminated (I suspect that the IFD at `0x3DE` should have just indicated the end, as the IDF at `0x480` doesn't look like one).

I'll submit a patch for the error checks that we don't do, but other than that I am out of ideas.

**Comment by clanmills** [comment] 2017-11-08 01:45
I'll have a look at this.  I returned to England yesterday.  In a couple of days, I'll be over my jet-lag.

The 6 weeks trip "home" to the States has been a blast.  I'm so happy with the work than you and Luis and Michal have done while I've been away.  Thanks You All.

**Comment by potuz** [comment] 2017-11-09 20:10
For what its worth, given the dates and the fact that this happens with only some of my photos, it seems to me that the files where this happens are some old photos where I was editing exif data in the file. If I recall correctly with ufraw.  I think only the pictures with some tags and/or rating added are the ones that raise this issue.

**Comment by clanmills** [comment] 2017-11-09 20:22
I’ll have a look at this.  This issue was introduced by promoting that function from being a debugging function in v0.25 (Exiv2 -pS image ...) to being the primary tiff parser in 0.26.  The reason to promote the code is documented in Work-in-Progress.

Robin
http://clanmills.com
Not sent from my iPhone

**Comment by D4N** [comment] 2017-11-09 22:46
Ah, good to know. I just checked the file with 0.25 and it produces the following output on stderr:
`Error: Directory (Last IFD item): Next pointer is out of bounds; ignored.`

**Comment by potuz** [comment] 2017-11-09 23:13
Many of my CR2 files taken (even today) with that old Canon and with no editing produce that error or similar on 0.26, for example
```
invalid type value detected in Image::printIFDStructure:  32767
Warning: Directory Canon has an unexpected next pointer; ignored.
```

**Comment by clanmills** [comment] 2017-11-09 23:37
Relax.  I think we’ll get a simple fix for your .cr2 files this tomorrow.

I’ve discussed wider implications about the structure of Exiv2 with Dan.  We’ll do something about this quite quickly and apply more robust changes later.

We are having a Team Meeting on Sunday.  You welcome to join us if you wish.

Robin
http://clanmills.com

**Comment by traceprobe** [comment] 2018-04-17 20:33
It seems that the issue is still there. (./exiv2 -pt ATTACHED_FILE). Have you come up with a fix?
[exiv2_0-26_exiv2_infinite_loop_printIFDStructure.jpg.zip](https://github.com/Exiv2/exiv2/files/1921492/exiv2_0-26_exiv2_infinite_loop_printIFDStructure.jpg.zip)

**Comment by clanmills** [comment] 2018-04-18 13:15
I assure that this matter has been given attention, however the fix has not yet integrated with 'master'.  The team is having a meeting at my home in England on May 5&6 and O hope we'll be able to resolve and close these issues at that time.  Please be in no doubt that this is has been, and will be, given attention.

**Comment by potuz** [comment] 2018-05-16 22:51
I was wandering if this issue was addressed in that meeting or if you guys think there might be a timeline. My original problem was trying to import to digiKam, I could try to patch that directly to prevent it from using exiv2 but that might also take some time.

**Comment by clanmills** [comment] 2018-05-17 05:39
We didn't discuss your issue on its own.  However we extensively discussed the issue of image::printStructure().  We hope to release Exiv2 v0.27 towards the end of 2018 and reach RC1 in the Fall.

The issue you have raised involved "fuzzed" files.  These are illegal files which cause exiv2 to crash and the fix for those files is the top priority feature of Exiv2 v0.27.  Additionally, we intend to make regular "dot" releases of v0.27 in 2019 to deal with crashes discovered after we release v0.27.  https://github.com/Exiv2/exiv2/issues/225

**Comment by clanmills** [comment] 2018-05-17 11:07
We're talking about 2 different files.  The JPEG is 95 bytes and I believe is a fuzzed file.  The CR2 mentioned in the title appears to be from a Canon camera.
```
-rw-------@ 1 rmills  staff    95B 17 Apr 21:32 exiv2_0-26_exiv2_infinite_loop_printIFDStructure.jpg
-rw-r-----@ 1 rmills  staff  9521648  7 Nov  2017 /Users/rmills/Downloads/IMG_0186.CR2
```
The subject printStructure() is being dealt with for v0.27 and receiving attention.

**Comment by potuz** [comment] 2018-09-30 19:38
Thanks! the latest commits solved this issue for me. This could be closed for all I know

**Comment by D4N** [comment] 2018-10-07 08:43
Unfortunately not yet, I think you'll still be able to reproduce the infinite loop with `exiv2 -pR $file`.

**Comment by piponazo** [comment] 2018-11-07 12:45
Hi. After the latest fixes in `printIFDStructure` it seems that the infinite loop is gone: 

```
13:43 $ bin/exiv2 -pR  /tmp/IMG_0186.CR2
STRUCTURE OF TIFF FILE (II): /tmp/IMG_0186.CR2
 address |    tag                              |      type |    count |    offset | value
      18 | 0x0100 ImageWidth                   |     SHORT |        1 |           | 1536
      30 | 0x0101 ImageLength                  |     SHORT |        1 |           | 1024
      42 | 0x0102 BitsPerSample                |     SHORT |        3 |       190 | 8 8 8
      54 | 0x0103 Compression                  |     SHORT |        1 |           | 6
      66 | 0x010f Make                         |     ASCII |        6 |       196 | Canon
      78 | 0x0110 Model                        |     ASCII |       27 |       202 | Canon EOS DIGITAL REBEL XT
      90 | 0x0111 StripOffsets                 |      LONG |        1 |           | 9728
     102 | 0x0112 Orientation                  |     SHORT |        1 |           | 1
     114 | 0x0117 StripByteCounts              |      LONG |        1 |           | 640258
     126 | 0x011a XResolution                  |  RATIONAL |        1 |       234 | 72/1
     138 | 0x011b YResolution                  |  RATIONAL |        1 |       242 | 72/1
     150 | 0x0128 ResolutionUnit               |     SHORT |        1 |           | 2
     162 | 0x0132 DateTime                     |     ASCII |       20 |       250 | 2006:05:05 09:00:05
     174 | 0x8769 ExifTag                      |      LONG |        1 |           | 270
  STRUCTURE OF TIFF FILE (II): /tmp/IMG_0186.CR2
   address |    tag                              |      type |    count |    offset | value
       272 | 0x829a ExposureTime                 |  RATIONAL |        1 |       612 | 1/800
       284 | 0x829d FNumber                      |  RATIONAL |        1 |       620 | 90/10
       296 | 0x8822 ExposureProgram              |     SHORT |        1 |           | 2
       308 | 0x8827 ISOSpeedRatings              |     SHORT |        1 |           | 1600
       320 | 0x9000 ExifVersion                  | UNDEFINED |        4 |           | 0221
       332 | 0x9003 DateTimeOriginal             |     ASCII |       20 |       628 | 2006:05:05 09:00:05
       344 | 0x9004 DateTimeDigitized            |     ASCII |       20 |       648 | 2006:05:05 09:00:05
       356 | 0x9101 ComponentsConfiguration      | UNDEFINED |        4 |           | ...
       368 | 0x9201 ShutterSpeedValue            | SRATIONAL |        1 |       668 | 632020/65536
       380 | 0x9202 ApertureValue                |  RATIONAL |        1 |       676 | 415488/65536
       392 | 0x9204 ExposureBiasValue            | SRATIONAL |        1 |       684 | 0/2
       404 | 0x9207 MeteringMode                 |     SHORT |        1 |           | 5
       416 | 0x9209 Flash                        |     SHORT |        1 |           | 16
       428 | 0x920a FocalLength                  |  RATIONAL |        1 |       692 | 28/1
       440 | 0x927c MakerNote                    | UNDEFINED |     8340 |       700 | ......................@........ ...
    STRUCTURE OF TIFF FILE (II): /tmp/IMG_0186.CR2
     address |    tag                              |      type |    count |    offset | value
         702 | 0x0001 Version                      |     SHORT |       46 |       996 | 92 2 0 4 0 ...
         714 | 0x0002 ISOSpeed                     |     SHORT |        4 |      1088 | 1 28 907 605
         726 | 0x0003 ColorMode                    |     SHORT |        4 |      1096 | 100 0 0 0
         738 | 0x0004 Quality                      |     SHORT |       34 |      1104 | 68 0 288 228 203 ...
         750 | 0x0006 Sharpening                   |     ASCII |       32 |      1172 | Canon EOS DIGITAL REBEL XT.....
         762 | 0x0007 Focus                        |     ASCII |       32 |      1204 | Firmware 1.0.3.................
         774 | 0x0009 GPSStatus                    |     ASCII |       32 |      1236 | unknown.....<.......P.......d..
         786 | 0x000c GPSSpeedRef                  |      LONG |        1 |           | 1520725789
         798 | 0x000d GPSSpeed                     | UNDEFINED |     1024 |      1268 | ............................... ...
         810 | 0x000f ISOSelection                 |     SHORT |       10 |      2340 | 20 0 256 512 768 ...
         822 | 0x0010 DataDump                     |      LONG |        1 |           | 2147484041
         834 | 0x0012 GPSMapDatum                  |     SHORT |       24 |      2292 | 7 7 3456 2304 3456 ...
         846 | 0x0013 GPSDestLatitudeRef           |     SHORT |        4 |      2360 | 0 159 7 112
         858 | 0x0015 GPSDestLongitudeRef          |      LONG |        1 |           | 2684354560
         870 | 0x0019 GPSDestDistanceRef           |     SHORT |        1 |           | 1
         882 | 0x0083                              |      LONG |        1 |           | 0
         894 | 0x0093                              |     SHORT |       16 |      2368 | 32 6464 186 0 0 ...
         906 | 0x00a0                              |     SHORT |       14 |      2400 | 28 0 0 0 0 ...
         918 | 0x00aa                              |     SHORT |        5 |      2428 | 10 430 1024 1024 648
         930 | 0x00d0                              |      LONG |        1 |           | 0
         942 | 0x00e0                              |     SHORT |       17 |      2438 | 34 3516 2328 1 1 ...
         954 | 0x4001                              |     SHORT |      582 |      2472 | 1164 848 1024 1024 357 ...
         966 | 0x4002                              |     SHORT |     2676 |      3636 | 5352 0 0 0 5657 ...
         978 | 0x4003                              |     SHORT |       22 |      8988 | 0 0 0 0 0 ...
Exiv2 exception in print action for file /tmp/IMG_0186.CR2:
corrupted image metadata
```
The same happens with the issue #373. Should we close these issues now ?

**Comment by clanmills** [comment] 2018-11-07 13:02
I think we're coming to the end of this misery.

I believe we agreed (in England) that the command `$ exiv2 -pR image-path ...` would only execute on DEBUG builds.  We might need a new exception to deal with that (for sure another localisation string).  Something like "option only supported on DEBUG builds".  We shouldn't mention `-pR` as we might want to use this feature of exiv2(.exe) for other options (and/or other sample programs).

We can't remove `printStructure()` because it's used by `-pS`, `-pC`, `-pX` (and possibly other options).  When/if the BigTiff project proceeds in v0.28, all of this will be re-engineered.

**Comment by clanmills** [comment] 2018-11-29 18:15
I think we've beaten this to death.  The proposal to only offer -pR in the exiv2 command-line program in DEBUG builds has been implemented.  Many issues concerning `printStructure()` have been reported and fixed.  We will reach Exiv2 v0.27 RC3 tomorrow (2018-11-30).  Time to close this.

**Closed by clanmills** 2018-11-29 18:15 UTC
Labels: printStructure
