### ISSUE TITLE
Support for files from OM System cameras

### ISSUE THREAD

**Issue by sarunasb** [Exiv2/exiv2#2126] opened 2022-03-06 01:10 UTC
##### **Is your feature request related to a problem?**
Currently exiv2 reports errors 
`Error: XMP Toolkit error 201: Error in XMLValidator
Warning: Failed to decode XMP metadata.`
for files from the newly release OM System OM-1 camera. 

##### **Describe the solution you would like**
Would like exiv2 to fully decode metadata in files from OM System cameras.

Please find a sample JPG file from OM-1 camera attached.

![OM100001](https://user-images.githubusercontent.com/725156/156904950-ccde5f9f-0740-4d45-af22-e8c333636753.JPG)

**Comment by kmilos** [comment] 2022-03-06 20:22
There are potentially two separate issues here: the XMP payload strangeness, and then the MakerNotes (OLYMPUS -> "OM SYSTEM"). Might take a look when I get a chance...

**Comment by clanmills** [comment] 2022-03-06 21:43
There's something wrong with the XMP metadata in that file.  The data is:

```bash
547 rmills@rmillsm1:/etc/apache2 $ exiv2 -pX ~/Desktop/OM.JPG  | xmllint --pretty 1 -
<?xml version="1.0"?>
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" rdf:about="" xmp:Rating="0"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
548 rmills@rmillsm1:/etc/apache2 $ 
```
It looks very innocent, however the XMPsdk built into Exiv2 dislikes if for reasons I don't know.  I don't think there's anything interesting in that XMP metadata.  You could easily write a script to remove the XMP metadata and your file will be good to go.  If you subsequently write XMP metadata into the file, Exiv2 will use its built-in XMPsdk to write good metadata.



Here's the XMP in one of my files (which I edited with Picasa).  Looks almost as boring.  It does have the additional magic `x:xmptk="XMP Core 5.1.2"`.  Maybe that's significant.  I'll need to step your file in the debugger in XMPsdk to discover why he dislikes the code in OM.JPG.

```bash
593 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ exiv2 -pX ~/Stonehenge.jpg | xmllint --pretty 1 -
<?xml version="1.0"?>
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.1.2">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/" rdf:about="" xmp:Rating="0" xmp:ModifyDate="2015-07-16T20:25:28+01:00">
      <dc:description>
        <rdf:Alt>
          <rdf:li xml:lang="x-default">Classic View</rdf:li>
        </rdf:Alt>
      </dc:description>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
594 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ 
```

**Comment by clanmills** [comment] 2022-03-07 06:21
@kmilos is 100% correct in his diagnosis.  There are two issues with your file:

1.  XMP metadata _strangeness_
2.  MakerNote support for the OM.

The good news is that I know what's wrong with the XMP metadata in your file.  I also have positive news about the Olympus MakerNote decoder.

_**Good News and your XMP metadata**_

I don't understand the XMPsdk code.  It's abstract/template magic which I'm not clever enough to understand.  However, my guess about `x:xmptk="XMP Core 5.1.2"` is correct.  Here's what I've done. 

1.  The JPEG is a collection of "segments" and you can see the structure with the command:
```bash
$ exiv2 -pS OM.JPEG
```
 
2.  Chopped your file into two parts `start` and `end` using utility `dd`
3.  Extracted the XMP into file `xmp` and edited it to add `x:xmptk="XMP Core 5.1.2"`
6.  Spliced start xmp end  > OM2.jpg
```bash
541 rmills@rmillsmm-local:~/temp $ exiv2 -pS OM.JPEG 
STRUCTURE OF JPEG FILE: OM.JPEG
 address | marker       |  length | data
       0 | 0xffd8 SOI  
       2 | 0xffe1 APP1  |   39648 | Exif..II*........... ..........
   39652 | 0xffe1 APP1  |    2332 | http://ns.adobe.com/xap/1.0/.<?x
   41986 | 0xffdb DQT   |     132 
   42120 | 0xffc0 SOF0  |      17 
   42139 | 0xffc4 DHT   |     418 
   42559 | 0xffdd DRI   |       4 
   42565 | 0xffda SOS  
542 rmills@rmillsmm-local:~/temp $ dd bs=1 count=39652 if=OM.JPEG of=start
39652+0 records in
39652+0 records out
39652 bytes transferred in 0.213272 secs (185922 bytes/sec)
543 rmills@rmillsmm-local:~/temp $ dd bs=1 skip=$((41986-1)) count=11111111111111 if=OM.JPEG of=end
642636+0 records in
642636+0 records out
642636 bytes transferred in 3.736256 secs (172000 bytes/sec)
544 rmills@rmillsmm-local:~/temp $ exiv2 -pX OM.JPEG | xmllint --pretty 1 - > xmp
545 rmills@rmillsmm-local:~/temp $ bbedit xmp
546 rmills@rmillsmm-local:~/temp $ cat xmp
<?xml version="1.0"?>
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.1.2">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" rdf:about="" xmp:Rating="0"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
547 rmills@rmillsmm-local:~/temp $ cat start xmp end > OM2.JPEG
```

_**Olympus MakerNote Decoder**_

The makernote decoder isn't working on your file.  Exiv2 supports Olympus cameras, and the MakerNote is an embedded Tiff in your file.  It's likely that the OM is using a similar _yet different_ header from other Olympus cameras.  It needs to be investigated. It might be an easy change to support this.

```bash
548 rmills@rmillsmm-local:~/temp $ exiv2 -pa OM2.JPEG 
Exif.Image.ImageDescription                  Ascii      32  
Exif.Image.Make                              Ascii      24  OM Digital Solutions   
Exif.Image.Model                             Ascii      17  OM-1            
...
Exif.Photo.MakerNote                         Undefined 20156  79 77 32 83 89 83 84 69 ...  0 0 0 0
Exif.Photo.UserComment                       Undefined 125                                                                                                                       
...
549 rmills@rmillsmm-local:~/temp $ 
```

_**What to do about this?**_

it comes down to the availability of an engineer to work on this.

We should read the XMP specification.  If a valid version of `x:xmptk="XMP Core 5.1.2"` is required by the Specification, then this is a bug in the OM firmware.

It may be possible to "tweak" the Adobe XMPsdk to be less nervous about the XMP _strangeness_.  

It's easy to write a script to fix the XMP _strangeness_.  My feeling is that the simplest way to do that is to totally remove the XMP metadata from your files.  A script using `exiv2 -pS`,  `dd` and `cp` is only a few lines of bash (or python or almost anything).

We'll need a volunteer to investigate the Olympus MakerNote.  I'm not volunteering as I have retired.  I've looked at this to "scope" the issue, however I no longer modify Exiv2 code.

**Comment by postscript-dev** [comment] 2022-03-07 08:45
@sarunasb :
Before uploading your test image, did you copy it directly from your camera or process it with software first? If software edited the metadata, the XMP problem may be caused by that.

As I already have other projects to work on, I can't commit to fixing this.

**Comment by kmilos** [comment] 2022-03-07 09:26
@clanmills Thanks for the initial snoop and pointers!

The XMP strangeness is present also w/ ORF raw files (presumably directly from camera, samples should be appearing on raw.pixls.us sometime soon I hope), here's a similar dump missing the said field:

```
<?xpacket begin="ï»¿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmp:Rating="0"/>
 </rdf:RDF>
</x:xmpmeta>
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                        <?xpacket end="w"?>

```

I might play w/ subclassing the MakerNotes at some point, but XMP parsing is beyond me for now...

**Comment by kmilos** [comment] 2022-03-07 09:58
From a quick look at https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf (2012 version though, there is a 2019 revision behind the ISO paywall), there is no mention of mandatory `x:xmptk` attribute:

![image](https://user-images.githubusercontent.com/4973094/157009060-8309e9db-2361-499f-95da-825e53b7308b.png)

**Comment by clanmills** [comment] 2022-03-07 10:16
Always good to hear from you, @kmilos.  I can decode MakerNotes in tvisitor.  Straight forward.  Later today, I'll update issue report concerning the MakerNote.

There is an exiv2 command-line option `-dx` to say "remove the XMP".  It's working, _although it's pumping out the SDK warning_.

```bash
691 rmills@rmillsmm-local:~/gnu/github/exiv2/team.exiv2.org/book/build $ cp ~/temp/OM.JPEG .
692 rmills@rmillsmm-local:~/gnu/github/exiv2/team.exiv2.org/book/build $ exiv2 -pS OM.JPEG 
STRUCTURE OF JPEG FILE: OM.JPEG
 address | marker       |  length | data
       0 | 0xffd8 SOI  
       2 | 0xffe1 APP1  |   39648 | Exif..II*........... ..........
   39652 | 0xffe1 APP1  |    2332 | http://ns.adobe.com/xap/1.0/.<?x
   41986 | 0xffdb DQT   |     132 
   42120 | 0xffc0 SOF0  |      17 
   42139 | 0xffc4 DHT   |     418 
   42559 | 0xffdd DRI   |       4 
   42565 | 0xffda SOS  
693 rmills@rmillsmm-local:~/gnu/github/exiv2/team.exiv2.org/book/build $ exiv2 -dx OM.JPEG 
Error: XMP Toolkit error 201: Error in XMLValidator
Warning: Failed to decode XMP metadata.
694 rmills@rmillsmm-local:~/gnu/github/exiv2/team.exiv2.org/book/build $ exiv2 -pS OM.JPEG 
STRUCTURE OF JPEG FILE: OM.JPEG
 address | marker       |  length | data
       0 | 0xffd8 SOI  
       2 | 0xffe1 APP1  |   39648 | Exif..II*........... ..........
   39652 | 0xffdb DQT   |     132 
   39786 | 0xffc0 SOF0  |      17 
   39805 | 0xffc4 DHT   |     418 
   40225 | 0xffdd DRI   |       4 
   40231 | 0xffda SOS  
695 rmills@rmillsmm-local:~/gnu/github/exiv2/team.exiv2.org/book/build $ 
```

Thanks for reading the XMP spec.  It's written in the terse language of a spec lawyer!  It doesn't dictate anything about the attribute `x:xmptk` _(="XMP Core 5.1.2")_.

I looked at the XMPsdk code earlier, it's another tough-to-understand son-of-a-bitch.  We might be able to change the options to ParseFromBuffer() to ignore xmptk and save the day.

More later.

**Comment by kmilos** [comment] 2022-03-07 10:29
[The failure seems to happen very early, raised by expat parsing](https://github.com/Exiv2/exiv2/blob/02b0541bbf65568cdca6c1d4faedf68b15a3ea15/src/xmp.cpp#L110), way before we look into the XMP itself...

**Comment by clanmills** [comment] 2022-03-07 10:41
Really?  It's valid XML.

Thanks for the pointer to `check_internal()`.  I'll sniff around in there.

**Comment by sarunasb** [comment] 2022-03-07 12:22
> 



> @sarunasb : Before uploading your test image, did you copy it directly from your camera or process it with software first? If software edited the metadata, the XMP problem may be caused by that.

The uploaded JPEG file was copied directly from SD card. No processing outside of camera firmware. The "picture" was taken with the lens cap on.

**Comment by sarunasb** [comment] 2022-03-07 12:24
> The XMP strangeness is present also w/ ORF raw files (presumably directly from camera, samples should be appearing on raw.pixls.us sometime soon I hope)

@clanmills Thank you for analysing the file!
I have already uploaded RAW ORF samples to raw.pixls.us several days ago.

**Comment by kmilos** [comment] 2022-03-07 12:29
> I have already uploaded RAW ORF samples to raw.pixls.us several days ago.

I know, that's why I said it should appear there soon (fingers crossed; it undergoes a manual review by the RPU maintainer...)

**Comment by clanmills** [comment] 2022-03-07 12:31
There may be something wrong with the XML packet.  buflen == 2301 and that seems correct to me.  The XML finishes with: 
```
</x:xmpmeta>. == 
44 46 3e 0a 3c 2f 78 3a 78 6d 70 6d 65 74 61 3e 0a 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
 D  F  > nl  <  /  x  :  x  m  p  m  e  t  a  > nl sp sp ......> to the endi                
```
I think the `nl` after the closing `>` may be upsetting XML_Parse().  Hard to believe. For sure something is causing this.

**Comment by hassec** [comment] 2022-03-07 12:39
I'm guessing/hoping that the firmware will pretty much be that of an Olympus camera.    
(MakerNote is located `0x927c` which is the same location as in Olympus cameras so that makes me think my hope might be true.)  

In that case we might be able to just "massage" the makernote creation to also create Olympus makernotes for `OM` cameras.   
I've not yet had the time to try but figured I'd dump what I know in case someone wants to give it a shot. 

The creation of a makernote goes through [`TiffMnCreator::create()`](https://github.com/Exiv2/exiv2/blob/main/src/makernote_int.cpp#L148) 

which uses the `registry_` that doesn't know about cameras with the make `OM Digital Solutions`: 
https://github.com/Exiv2/exiv2/blob/02b0541bbf65568cdca6c1d4faedf68b15a3ea15/src/makernote_int.cpp#L106-L115  

so that `registry_` as well as the family of  `newOlympusMn()` functions would need to be adapted to understand the new `OM Digital Solutions` string inside the makernote.

**Comment by kmilos** [comment] 2022-03-07 12:42
@hassec Exactly, it should hopefully just be a matter of supporting the new "OM SYSTEM" MakerNote signature/header through new subclasses...

**Comment by kmilos** [comment] 2022-03-07 12:51
> I think the `nl` after the closing `>` may be upsetting XML_Parse(). Hard to believe.

It is hard to believe. I tried replacing with \x00 in a hex editor, and the XML validation error persists

**Comment by clanmills** [comment] 2022-03-07 13:12
@hassec @kmilos The changes to the Olympic MakerNote are easy.  I have them working in tvisitor.cpp.  I'm focused on understanding what's upsetting XMP_Parse().

I think my earlier fix involving `x:xmptk="XMP Core 5.1.2"` is totally wrong.  That worked for two reasons:

1. I removed the http://ns.adobe.com/xap/1.0/.<?x signature in the OM2.JPEG, so the XML wasn't read by the XMPsdk.
2. I sanitized the XML in the editor.

Relax Everybody:  This will be simple when we find it _which we will_.

**Comment by clanmills** [comment] 2022-03-07 15:10
There's something wrong with the XMP buffer.  I'm cross-eyed with this.  It's got to be simple - a trailing null byte _(or something like that)_.  I'm 100% certain that it is not `x:xmptk="XMP Core 5.1.2"`.  _I can prove that, if you ask_.

The changes to tvisitor to support this are two fold:

1.  The maker note handler must deal with the new MakerNote header `OM SYSTEM\0II`.  It's almost exactly the same as the existing `OLYMPUS\0II` header.

```cpp
case kOlym:
    if ( buf.begins("OLYMPUS\0II")        // "OLYMPUS\0II\0x3\0x0"short      0x3\0x0   version?  short = E# (dictionary count)
    ||   buf.begins("OM SYSTEM\0\0II")    // "OM SYSTEM\0\0II\0x4\0x7"short  0x04 0x07 version?  short = E#
    ) { 
        Io     io(io_,offset,count);
        TiffImage makerNote(io,image_.maker_);
        makerNote.start_ =  buf.begins("OLYMPUS\0II") ? 12 : 16 ;
        makerNote.valid_ = true; // Valid without magic=42
        makerNote.accept(visitor,makerDict());
    } else {                              // "OLYMP\0bytebyteshort"          bytebyte  version?  short = E#
        size_t punt = 8 ;                 // "OLYMPUS\0short"                                    short = E#
        IFD makerNote(image_,offset+punt,false);
        makerNote.accept(visitor,makerDict());
    } break;
```

2.  The makers dictionary has to know that Exif.Image.Make =  "OM Digital Solutions" is an olymDict.

```cpp
makers["Canon"      ]  = kCanon  ; makerDicts[kCanon ] = &canonDict;
...
makers["OLYMPUS"    ]  = kOlym   ; makerDicts[kOlym  ] = &olymDict;
makers["OM Digital Solutions"]
                       = kOlym   ; makerDicts[kOlym  ] = &olymDict;
makers["FUJIFILM"   ]  = kFuji   ; makerDicts[kFuji  ] = &fujiDict;
makers["PENTAX"     ]  = kPentax ; makerDicts[kPentax] = &pentaxDict;
```

The tvisitor makernote code cannot be cut'n'pasted into Exiv2, so somebody will have to figure what I've said and how to represent it in the exiv2 code base.

I don't want to get further sucked into this.  I'll be curious to learn what I cannot spot about the XMP.  It will be obvious.

**Comment by piponazo** [comment] 2022-03-07 16:57
> @clanmills Ah, this could be [libexpat/libexpat#572](https://github.com/libexpat/libexpat/issues/572) that was fixed recently. 2.4.7 should land in MSYS2 in the next couple of days so I'll test it then.

Ha, interesting, we should also update the conanfile so that we bring the newest version of expat (2.4.7) when it is available. Right now, in the conan center repository the latest available version is 2.4.6:

https://conan.io/center/expat

And currently we are requiring the usage of 2.4.1:
https://github.com/Exiv2/exiv2/blob/02b0541bbf65568cdca6c1d4faedf68b15a3ea15/conanfile.py#L40

**Comment by kmilos** [comment] 2022-03-07 18:19
Actually I already have 2.4.7 on MSYS2, so not it 😖

**Comment by clanmills** [comment] 2022-03-07 19:56
Solved.   It's the trailing \0 and \n bytes _which is what I thought this morning_.

```bash
1012 rmills@rmillsmm-local:~/gnu/github/exiv2/main/build $ env DYLD_LIBRARY_PATH=$PWD/lib bin/exiv2 -vVg exiv2
exiv2 1.0.0.9
exiv2=1.0.0
processpath=/Users/rmills/gnu/github/exiv2/main/build/bin
package_name=exiv2
executable=/Users/rmills/gnu/github/exiv2/main/build/bin/exiv2
library=/Users/rmills/gnu/github/exiv2/main/build/lib/libexiv2.1.0.0.9.dylib
config_path=/Users/rmills/.exiv2
1013 rmills@rmillsmm-local:~/gnu/github/exiv2/main/build $ env DYLD_LIBRARY_PATH=$PWD/lib bin/exiv2 ~/temp/OM.JPEG 
File name       : /Users/rmills/temp/OM.JPEG
File size       : 684621 Bytes
MIME type       : image/jpeg
Image size      : 5184 x 3888
Thumbnail       : image/jpeg, 968 Bytes
Camera make     : OM Digital Solutions   
Camera model    : OM-1            
Image timestamp : 2022:03:05 14:05:59
File number     : 
Exposure time   : 1/250 s
Aperture        : F5.6
Exposure bias   : 0 EV
Flash           : Yes, did not fire
Flash bias      : 
Focal length    : 12.0 mm
Subject distance: 
ISO speed       : 200
Exposure mode   : Manual
Metering mode   : Multi-segment
Macro mode      : 
Image quality   : 
White balance   : Manual
Copyright       : Sarunas Burdulis                                               
Exif comment    :       
1014 rmills@rmillsmm-local:~/gnu/github/exiv2/main/build $ env DYLD_LIBRARY_PATH=$PWD/lib bin/exiv2 -px ~/temp/OM.JPEG 
Xmp.xmp.Rating                               XmpText     1  0
1015 rmills@rmillsmm-local:~/gnu/github/exiv2/main/build $ env DYLD_LIBRARY_PATH=$PWD/lib bin/exiv2 -K Exif.Image.Make  ~/temp/OM.JPEG 
Exif.Image.Make                              Ascii      24  OM Digital Solutions   
1016 rmills@rmillsmm-local:~/gnu/github/exiv2/main/build $                                                                                                                
```

Here's the one-line fix.  

```cpp
             while ( 0 < (int) buflen && (buf[buflen-1] == 0 || buf[buflen-1] == 10) ) buflen--;
```

The patch.  (Please don't submit the three commented off lines _you'll find them useful to debug/verify the fix_.).

```diff
diff --git a/src/xmp.cpp b/src/xmp.cpp
index 133d38d6..1c78eb5c 100644
--- a/src/xmp.cpp
+++ b/src/xmp.cpp
@@ -101,6 +101,10 @@ namespace {
             if (buflen > static_cast<size_t>(std::numeric_limits<int>::max())) {
                 throw Error(kerXMPToolkitError, "Buffer length is greater than INT_MAX");
             }
+            //for ( int i = (int) buflen - 5 ; i < (int)buflen ; i++ ) {
+            //    std::cout <<  i << ':' <<  (int) buf[i] << std::endl;
+            //}
+            while ( 0 < (int) buflen && (buf[buflen-1] == 0 || buf[buflen-1] == 10) ) buflen--;
 
             XML_SetUserData(parser_, this);
             XML_SetElementHandler(parser_, startElement_cb, endElement_cb);
```

I don't know if I can hear you groaning or giving me a cheer.

**Comment by kmilos** [comment] 2022-03-07 20:28
Both?

But it's incredulous libexpat doesn't tolerate LF and NUL surplus at the end and doesn't do this chomping internally... I feel like we should report it, unless I'm missing something about XML rules?

**Comment by clanmills** [comment] 2022-03-07 21:51
Yup.  Both.  Shit, isn't it?  Reporting a bug to expat?  I don't think I'm brave enough.

I reviewed and approved Kev's `check_internal()` function and asked him to add it to 0.27-maintenance.  I wonder if XMPsdk deals with this quietly.  I'll run an old release (such as 0.27) on that file.

I'm running a test on all my 80,000 photos to see how many `XML Validator` errors have been fixed.  These are quite common when files have been edited _(usually by non-Adobe products)_.  I'll run the same test with 0.27.  This could be a wonderful and surprising find.

**Comment by kmilos** [comment] 2022-03-07 21:55
FYI, my trials were all w/ 0.27.5

**Comment by clanmills** [comment] 2022-03-07 22:00
I think `check_internal()` was added to 0.27.4 or 0.27.5 (Summer 2021, I think).  That's why I thinking to use 0.27 for an old test..  `check_internal()` was added after 0.27 (December 2018).

**Comment by clanmills** [comment] 2022-03-07 23:04
| Exiv2 Build | Validator Errors<br>(from 80,000 images) |
|:-      |:- |
| 'main' + fix | 151 |
| '0.27-maintenance'  | To be done _(more for sure)_ |
| '0.27.0' | To be done |

I'll edit this table tomorrow when the tests have finished.

**Comment by kmilos** [comment] 2022-03-16 10:48
@hassec As for the MakerNote, I tried following the Sigma/Foveon example where we have two signatures for the same structure. Alas, it doesn't work out automagically here as the signatures are not of the same length so it is not that straightforward. I stopped going down the rabbit hole for the moment, so any ideas on how to handle this best are welcome.

**Comment by clanmills** [comment] 2022-03-16 14:50
@kmilos and @hassec  I'm happy to look at this, if you wish.   Is the "Sigma/Foveon" example, the image attached above:

```
$ ls -l ~/Downloads/OM.JPEG 
-rw-r--r--@ 1 rmills  staff  684621 16 Mar 14:15 /Users/rmills/Downloads/OM.JPEG
$ 
```

I haven't understood your comment: _we have two signatures for the same structure_.  The changes in tvisitor were straightforward https://github.com/Exiv2/exiv2/issues/2126#issuecomment-1060792127

Both tvisitor and exiv2 marker note decoder know the offset in the MakerNote tag to the IFD.  tvisitor is simpler because it detects Exif.Image.Make while parsing IFD0.  Exiv2 uses `class TiffFinder` to search from the MakerNote code.

The exiv2 code has a state machine which isn't needed by tvisitor.  The state machine is used to determine which makernote decoder to execute _(or something like that)_.  I'll have to refresh my memory about this, however I'm optimistic that the change will be small _(probably one line of code)_.  

Would you like me to look at this?

**Comment by kmilos** [comment] 2022-03-16 15:17
> I'm optimistic that the change will be small _(probably one line of code)_

Unfortunately not the case w/ the current architecture I'm afraid.

**Comment by clanmills** [comment] 2022-03-16 15:24
Would you like me to investigate?

**Comment by kmilos** [comment] 2022-03-16 15:33
Feel free, by all means.

I didn't find a better way than to [duplicate and create the entire new Olympus3MnHeader class](https://github.com/Exiv2/exiv2/blob/b2b6d834baf387425fab1a6b18aafee0e06b6e9a/src/makernote_int.cpp#L233-L276) and all the plumbing around it to connect it to the existing Olympus MakerNote structure.

**Comment by clanmills** [comment] 2022-03-16 15:35
Oh, man, that doesn't sound good.  The test file is the one attached?

```bash
$ ls -l ~/Downloads/OM.JPEG 
-rw-r--r--@ 1 rmills  staff  684621 16 Mar 14:15 /Users/rmills/Downloads/OM.JPEG
```

It's a really wet day in England.  I'll look at this.

**Comment by kmilos** [comment] 2022-03-16 16:05
Yep, the OP attached JPEG has the new "OM SYSTEM" MakerNote.

**Comment by clanmills** [comment] 2022-03-16 19:03
The pattern is:

header:  [alpha]+\0IIversion\_\_IFD\_\_
title: [alpha]+  
version: short eg 0x0300 or 0x0407
\_\_IFD\_\_ is E# ENTRY ENTRY ENTRY ...
E# is a short (number of entries)
ENTRY is 12 bytes (tag, type, count, offset)

The "title" can be OLYMPUS or "OM SYSTEM".  We don't really care, it could be "DONALD DUCK" provided it is terminated by '\0' 'I' 'I'.

So the correct code will be something like this.  

```cpp
    TiffComponent* newOlympusMn(uint16_t    tag,
                                IfdId       group,
                                IfdId       mnGroup,
                                const byte* pData,
                                size_t size,
                                ByteOrder   /*byteOrder*/)
    {
        TiffComponent* result = nullptr;
        if ( enough(pData,size) ) {
            result = new TiffIfdMakernote(tag, group, mnGroup, new OlympusMn2Header);
            size_t offset = getOffset(pData) ; // usually 16 or 12;
            result.setStart(pData+offset);
        }
        return result;
    }
```
Classes such as OlympusMn2Header are very stiff and inflexible.  The code in tvisitor is much simpler and parses every makernote I have found!

**Comment by kmilos** [comment] 2022-03-16 19:22
Agreed that it's the header class creating the unnecessary friction here, but a) I don't particularly feel like taking on refactoring this now, and b) think we need a solution for possible 0.27.6 to enable various apps in the nearer term.

**Comment by kmilos** [comment] 2022-03-16 19:26
And while that is indeed the prevalent pattern for MakerNote signatures/headers, it is by no means a prescribed standard we can count on vendors sticking to, so anything really goes.

**Comment by clanmills** [comment] 2022-03-17 08:05
As the sun is shining today, I'm going to work in the garden.  I don't intend to do any more work on this issue unless asked to do so.

**Comment by sarunasb** [comment] 2022-03-24 16:59
@clanmills So this is asking you to help with Olympus/OM System MakerNote, whenever you feel like, on a rainy day... :) Thank you!

**Comment by clanmills** [comment] 2022-03-25 08:20
![275347210_1333647243800216_8489668274434268825_n (1)](https://user-images.githubusercontent.com/529982/160082045-866b2bfb-28f5-4c6a-b7dc-c92f374b1ee3.jpg)

**Comment by kmilos** [comment] 2022-03-25 08:54
While Robin is trimming his perfect garden on a perfect day, feel free to test the "dumb" patch (0.27 branch) by duplicating all the necessary classes and functions.

**Comment by sarunasb** [comment] 2022-03-25 17:16
Compiled 027_omsystem_mn branch. `exiv2 -pv ` outputs roughly the same amount of bytes from ORF samples from Olympus Pen-F and OM System OM-1.

Compiled darktable:master with rawspeed from kmilos:om-1, linked with Exiv2:027_omsystem_mn. darktable reports the same set of metadata for samples files from Pen-F and OM-1.

I'm glad to do any more sensible tests, if there is some established routine.

**Closed** 2022-03-28 18:48 UTC
Labels: bug, request, makerNote

**Comment by kmilos** [comment] 2022-10-26 10:25
Somebody should let OMDS know they're not following spec - the same nul terminated XML problem is present in the new OM-5...
