### ISSUE TITLE
In Exiv 0.27.6 there was an overload of ImageFactory::open taking std::wstring and it's gone in 0.28.0

### ISSUE THREAD

**Issue by gh-andre** [Exiv2/exiv2#2799] opened 2023-10-19 02:40 UTC
### Discussed in https://github.com/Exiv2/exiv2/discussions/2795

I was able to open any file on Windows in 0.27.6, such as _hello_🌎.jpg_ and in 0.28.0 all of the methods for UTF-16 paths are gone, removed in commit 7933ff401ddb9768502c36b1febea06b854e176a. This change makes Exiv2 usable on Windows only for Win-1252 characters, which is what `fopen` operates on. In order to open files with UTF-16 paths and names, one needs to use `_wfopen`. Can this change be reverted by any chance? If not, is there any replacement functionality planned? It is a pretty significant regression.

Thank you

**Comment by kmilos** [comment] 2023-10-19 07:06
Duplicate of https://github.com/Exiv2/exiv2/issues/2637 @piponazo 

Please search before opening new issues.

**Closed by kmilos** 2023-10-19 07:06 UTC
